#!/usr/bin/env python3
"""
publish_digest.py — 每日热帖「投递」编排（自己网站 + 企业微信）。

架构（见 SKILL.md）：
  取数(make_daily_digest) → agent 填 digest_spec → 校验(validate_digest)
      → 渲染(render_digest) → **投递(本文件)** → 双渠道触达

本文件职责（只做"投递"，不改格式）：
  1. 自己网站：render(spec, 'html') 落盘 → publish_gallery_html.py 使用当前用户 token
     上传 AI Gallery 并保持 visibility=self → 回读 display_url，写回 spec['detail_url']
     （渲染器底部链接自动带出）
  2. 企业微信：render(spec, 'markdown') → 按 4096 字分段推送到机器人 Webhook

设计原则：投递失败（Gallery / Webhook）降级而不阻断——网站发布失败保留本地
HTML 链接、继续推企微；任一渠道可单独关闭。

打点不在本文件：调用打点应在「取数时」由 agent 直接调 `report_log.py` CLI 完成
（见 SKILL.md），避免与取数重复计数。

CLI 示例：
  # 双渠道：上传网站 + 推企微
  python scripts/publish_digest.py --input /tmp/spec.json \\
      --webhook_url "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx"

  # 只预览渲染结果（不上传、不推送）
  python scripts/publish_digest.py --input /tmp/spec.json --preview_only

  # 只上传网站、不推企微
  python scripts/publish_digest.py --input /tmp/spec.json --no_webhook
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional
from urllib.request import Request, urlopen

_SCRIPTS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPTS_DIR))
from render_digest import render, _sample_spec  # noqa: E402

# 企业微信 markdown 单条上限（字符）；超长分段推送。
WECOM_MAX_CHARS = 4096

# [Why] 仅允许企业微信官方 Webhook 域名，避免 SSRF（file:// / localhost / 内网 IP 等）。
_ALLOWED_WEBHOOK_PREFIX = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send"

_GALLERY_SCRIPT = _SCRIPTS_DIR / "publish_gallery_html.py"


# ---------------------------------------------------------------------------
# 企业微信推送
# ---------------------------------------------------------------------------
def _validate_webhook_url(url: str) -> None:
    if not url.startswith(_ALLOWED_WEBHOOK_PREFIX):
        raise ValueError(
            f"webhook_url 必须以 {_ALLOWED_WEBHOOK_PREFIX} 开头，拒绝 {url[:60]!r}"
        )


def _chunk_message(content: str) -> list:
    """按 WECOM_MAX_CHARS 切分长消息。"""
    if len(content) <= WECOM_MAX_CHARS:
        return [content]
    return [content[i:i + WECOM_MAX_CHARS] for i in range(0, len(content), WECOM_MAX_CHARS)]


def _send_to_webhook(webhook_url: str, content: str) -> bool:
    _validate_webhook_url(webhook_url)
    chunks = _chunk_message(content)
    success = True
    for idx, chunk in enumerate(chunks, 1):
        if len(chunks) > 1:
            chunk = f"（{idx}/{len(chunks)}）\n" + chunk
        payload = json.dumps(
            {"msgtype": "markdown", "markdown": {"content": chunk}},
            ensure_ascii=False,
        ).encode("utf-8")
        req = Request(
            webhook_url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            resp = urlopen(req, timeout=15)
            body = json.loads(resp.read().decode("utf-8"))
            if body.get("errcode", -1) != 0:
                print(f"[WARN] Webhook 返回错误: {body}", file=sys.stderr)
                success = False
            else:
                print(f"[INFO] 推送成功（第 {idx} 段）", file=sys.stderr)
        except Exception as e:
            print(f"[ERROR] 推送失败: {e}", file=sys.stderr)
            success = False
    return success


def _resolve_webhooks(arg: str) -> list:
    """webhook 来源：--webhook_url 优先，回退 env WEBHOOK_URLS；均按 ; 分割。"""
    raw = (arg or os.environ.get("WEBHOOK_URLS", "")).strip()
    return [u.strip() for u in raw.split(";") if u.strip()]


# ---------------------------------------------------------------------------
# 自己网站（AI Gallery）
# ---------------------------------------------------------------------------
def _slugify(s: str) -> str:
    s = re.sub(r"[^0-9A-Za-z\u4e00-\u9fff]+", "_", str(s)).strip("_")
    return s[:40] or "digest"


def _render_html_to_file(spec: dict, html_dir: str) -> Path:
    html = render(spec, "html")
    ts = time.strftime("%Y%m%d-%H%M%S")
    fname = f"hotposts_{_slugify(spec.get('game_name', ''))}_{ts}.html"
    out = Path(html_dir) / fname
    out.write_text(html, encoding="utf-8")
    return out


def _publish_to_gallery(html_path: Path, game_name: str) -> Optional[str]:
    """调 publish_gallery_html.py 用当前用户 token 上传，返回 display_url；失败返回 None。"""
    title = f"{game_name} 每日热帖".strip() or "Databrain 每日热帖"
    name_cn = (f"{game_name} 每日热帖".strip() or "每日热帖")[:40]
    name_en = (f"{game_name} daily hot posts".strip() or "Daily hot posts")[:60]
    cmd = [
        sys.executable, str(_GALLERY_SCRIPT),
        "--file", str(html_path),
        "--title", title,
        "--name-cn", name_cn,
        "--name-en", name_en,
        "--desc-cn", "databrain-opinion-hotposts 自动生成的每日热帖榜单",
        "--desc-en", "Daily hot posts digest generated by databrain-opinion-hotposts",
    ]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=240, check=False)
    except Exception as exc:
        print(f"[WARN] AI Gallery 发布失败：{type(exc).__name__}: {exc}", file=sys.stderr)
        return None
    if proc.returncode != 0:
        msg = (proc.stdout or proc.stderr or "").strip()
        print(f"[WARN] AI Gallery 发布失败：{msg}", file=sys.stderr)
        return None
    try:
        payload = json.loads(proc.stdout.strip().splitlines()[-1])
    except Exception as exc:
        print(f"[WARN] AI Gallery 响应解析失败：{exc}; raw={proc.stdout[:300]!r}", file=sys.stderr)
        return None
    display_url = payload.get("display_url")
    if isinstance(display_url, str) and display_url:
        print(f"[INFO] AI Gallery 详情页：{display_url}", file=sys.stderr)
        return display_url
    print(f"[WARN] AI Gallery 未返回 display_url：{payload}", file=sys.stderr)
    return None


# ---------------------------------------------------------------------------
# 编排主流程
# ---------------------------------------------------------------------------
def publish(
    spec: dict,
    *,
    webhook_url: str = "",
    preview_only: bool = False,
    no_gallery: bool = False,
    no_webhook: bool = False,
    html_dir: str = "/tmp",
    detail_url_base: str = "",
) -> dict:
    game_name = spec.get("game_name", "")
    detail_url: Optional[str] = spec.get("detail_url")  # 保留 agent 已填的

    # 1) 自己网站
    if not (no_gallery or preview_only):
        try:
            html_path = _render_html_to_file(spec, html_dir)
        except Exception as e:
            print(f"[WARN] HTML 生成失败：{e}", file=sys.stderr)
            html_path = None
        if html_path:
            if detail_url_base:
                detail_url = f"{detail_url_base.rstrip('/')}/{html_path.name}"
            else:
                detail_url = _publish_to_gallery(html_path, game_name) or f"file://{html_path}"
            print(f"[INFO] 网站详情页：{detail_url}", file=sys.stderr)
    if detail_url:
        spec["detail_url"] = detail_url

    # 2) 渲染最终 markdown（底部链接会自动带出 detail_url）
    message = render(spec, "markdown")

    if preview_only:
        print("=== Preview (markdown) ===")
        print(message)
        print("=== End ===")
        return {"preview": True, "detail_url": detail_url, "sent": 0}

    # 3) 企业微信
    webhooks = [] if no_webhook else _resolve_webhooks(webhook_url)
    sent = 0
    push_ok = True
    if webhooks:
        for w in webhooks:
            if _send_to_webhook(w, message):
                sent += 1
            else:
                push_ok = False
    else:
        # 无 webhook：打印 markdown 供人工取用（网站若已发布仍然有效）
        print("[INFO] 未提供 webhook（--webhook_url / env WEBHOOK_URLS 均空），仅输出渲染结果。",
              file=sys.stderr)
        print(message)

    return {"preview": False, "detail_url": detail_url, "sent": sent, "push_ok": push_ok}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="每日热帖投递编排（当前用户 AI Gallery + 企业微信）；参见 SKILL.md",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--input", help="digest_spec.json 路径（已校验）")
    parser.add_argument("--webhook_url", default="",
                        help="企业微信 Webhook，多个用 ; 分隔；空则回退 env WEBHOOK_URLS，再空则只渲染不推")
    parser.add_argument("--preview_only", action="store_true",
                        help="只渲染 markdown 并打印，不上传网站、不推送")
    parser.add_argument("--no_gallery", action="store_true",
                        help="不使用当前用户 token 上传 AI Gallery（保留 spec 已有 detail_url）")
    parser.add_argument("--no_webhook", action="store_true", help="不推送企业微信")
    parser.add_argument("--html_dir", default="/tmp", help="HTML 落盘目录（默认 /tmp）")
    parser.add_argument("--detail_url_base", default="",
                        help="自托管网站时填 base URL 前缀；为空则默认用当前用户 token 上传 AI Gallery")
    parser.add_argument("--self_test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        sys.exit(_self_test())

    if not args.input:
        parser.error("--input 必传（digest_spec.json 路径）")

    try:
        spec = json.loads(Path(args.input).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(f"[ERROR] 读取 spec 失败: {e}", file=sys.stderr)
        sys.exit(1)

    result = publish(
        spec,
        webhook_url=args.webhook_url,
        preview_only=args.preview_only,
        no_gallery=args.no_gallery,
        no_webhook=args.no_webhook,
        html_dir=args.html_dir,
        detail_url_base=args.detail_url_base,
    )

    if result.get("preview"):
        return
    detail = result.get("detail_url")
    if detail:
        print(f"✅ 网站详情页：{detail}")
    sent = result.get("sent", 0)
    if sent:
        ok = result.get("push_ok", True)
        print(f"✅ 已推送企业微信 {sent} 个群。" if ok else f"⚠️ 推送 {sent} 个群，部分失败，请检查 Webhook。")
        if not ok:
            sys.exit(1)


# ---------------------------------------------------------------------------
# Self test（不联网）
# ---------------------------------------------------------------------------
def _self_test() -> int:
    fails: list = []

    def _check(name, ok, detail=""):
        if ok:
            print(f"  ✅ {name}")
        else:
            print(f"  ❌ {name}: {detail}")
            fails.append(name)

    print("=== publish_digest self test ===")

    # SSRF 白名单
    _check("webhook 接受 qyapi",
           _validate_webhook_url("https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=abc-123") is None)
    for bad in (
        "file:///etc/passwd",
        "http://localhost/abc",
        "http://169.254.169.254/latest/meta-data",
        "https://evil.example.com/cgi-bin/webhook/send?key=x",
        "https://qyapi.weixin.qq.com.evil.com/cgi-bin/webhook/send?key=x",
    ):
        try:
            _validate_webhook_url(bad)
            _check(f"webhook 拒绝 {bad[:32]}", False)
        except ValueError:
            _check(f"webhook 拒绝 {bad[:32]}", True)

    # 分段
    _check("短消息单段", _chunk_message("a" * 100) == ["a" * 100])
    long_chunks = _chunk_message("a" * (WECOM_MAX_CHARS * 2 + 10))
    _check("超长消息分 3 段", len(long_chunks) == 3, f"got={len(long_chunks)}")
    _check("分段无丢字", "".join(long_chunks) == "a" * (WECOM_MAX_CHARS * 2 + 10))

    # detail_url 注入 → markdown 底部带出网站链接
    spec = _sample_spec()
    spec.pop("detail_url", None)
    spec["detail_url"] = "https://databrain.woa.com/aigallery/report?path=%2Fx"
    md = render(spec, "markdown")
    _check("markdown 底部带出网站链接",
           "[在 DataBrain 查看完整列表](https://databrain.woa.com/aigallery/report?path=%2Fx)" in md,
           md[-200:])

    # slug 安全
    _check("slug 去非法字符", _slugify("PUBG Mobile / 国服!") == "PUBG_Mobile_国服")
    _check("slug 空回落", _slugify("") == "digest")

    # preview 渲染（不联网、不推送）
    res = publish(_sample_spec(), preview_only=True)
    _check("preview 返回 preview=True 且不推送", res["preview"] and res["sent"] == 0)

    print("\n" + "-" * 40)
    if fails:
        print(f"FAIL: {len(fails)}")
        return 1
    print("PASS: all publish_digest tests")
    return 0


if __name__ == "__main__":
    main()
