REGION_MAP_DASHBOARD = {
    "east europe": "EE",
    "japan and korea": "JK",
    "middle east": "ME",
    "north america": "NA",
    "overseas": "OVERSEAS",
    "海外": "OVERSEAS",
    "全球": "All Areas",
    "all areas": "All Areas",
    "south america": "SA",
    "south asia": "SAS",
    "south east asia": "SEA",
    "vietnam": "VN",
    "west europe": "WE",
    "东欧": "EE",
    "日韩": "JK",
    "中东": "ME",
    "北美": "NA",
    "南亚": "SAS",
    "越南": "VN",
    "西欧": "WE",
    "africa": "AF",
    "非洲": "AF",
    "antarctica": "AQ",
    "南极": "AQ",
    "caribbean": "CARIB",
    "加勒比": "CARIB",
    "china（mainland）": "CHN",
    "china": "CHN",
    "中国": "CHN",
    "中国大陆": "CHN",
    "europe": "EUR",
    "欧洲": "EUR",
    "欧美": ["EUR", "NA"],
    "亚洲": ["HMT", "CHN", "IN", "JPN", "KR", "SEA", "SAS", "OASIA"],
    "china（hongkong,macao,taiwan)": "HMT",
    "港台": "HMT",
    "港澳台": "HMT",
    "india": "IN",
    "印度": "IN",
    "japan": "JPN",
    "日本": "JPN",
    "south korea": "KR",
    "韩国": "KR",
    "oceania": "OA",
    "大洋洲": "OA",
    "other asia": "OASIA",
    "亚洲其他地区": "OASIA",
    "南美": "SA",
    "southeast asia": "SEA",
    "东南亚": "SEA",
}

REGION_MAP_INTEL = {
    "其他亚洲": ["BT", "LA", "MN", "LK"],
    "other asia": ["BT", "LA", "MN", "LK"],
    "港澳台": ["HK", "MO", "TW"],
    "hmt": ["HK", "MO", "TW"],
    "西欧": [
        "DK",
        "FI",
        "IS",
        "AT",
        "IE",
        "BE",
        "FR",
        "DE",
        "LU",
        "NL",
        "CH",
        "IT",
        "MT",
        "NO",
        "SE",
        "GB",
        "PT",
        "ES",
        "AD",
        "LI",
        "MC",
    ],
    "west europe": [
        "DK",
        "FI",
        "IS",
        "AT",
        "IE",
        "BE",
        "FR",
        "DE",
        "LU",
        "NL",
        "CH",
        "IT",
        "MT",
        "NO",
        "SE",
        "GB",
        "PT",
        "ES",
        "AD",
        "LI",
        "MC",
    ],
    "东欧": [
        "AM",
        "AZ",
        "TR",
        "EE",
        "AL",
        "BY",
        "HR",
        "BG",
        "CZ",
        "LV",
        "KZ",
        "KG",
        "LT",
        "TJ",
        "GR",
        "HU",
        "MD",
        "MK",
        "PL",
        "TM",
        "UZ",
        "RO",
        "RU",
        "SK",
        "SI",
        "UA",
        "GE",
        "RS",
        "BA",
    ],
    "east europe": [
        "AM",
        "AZ",
        "TR",
        "EE",
        "AL",
        "BY",
        "HR",
        "BG",
        "CZ",
        "LV",
        "KZ",
        "KG",
        "LT",
        "TJ",
        "GR",
        "HU",
        "MD",
        "MK",
        "PL",
        "TM",
        "UZ",
        "RO",
        "RU",
        "SK",
        "SI",
        "UA",
        "GE",
        "RS",
        "BA",
    ],
    "欧洲": ["ee", "we", "eur"],
    "europe": ["ee", "we"],
    "east europe": "ee",
    "eastern europe": "ee",
    "eeu": "ee",
    "非洲": [
        "TD",
        "MR",
        "BW",
        "GM",
        "GH",
        "KE",
        "LR",
        "MW",
        "MU",
        "NA",
        "NG",
        "SL",
        "ZA",
        "SZ",
        "TZ",
        "UG",
        "ZW",
        "BJ",
        "BF",
        "CG",
        "MG",
        "ML",
        "NE",
        "SN",
        "SC",
        "AO",
        "CV",
        "GW",
        "MZ",
        "ST",
        "ET",
        "CIV",
        "CU",
        "CD",
    ],
    "africa": [
        "TD",
        "MR",
        "BW",
        "GM",
        "GH",
        "KE",
        "LR",
        "MW",
        "MU",
        "NA",
        "NG",
        "SL",
        "ZA",
        "SZ",
        "TZ",
        "UG",
        "ZW",
        "BJ",
        "BF",
        "CG",
        "MG",
        "ML",
        "NE",
        "SN",
        "SC",
        "AO",
        "CV",
        "GW",
        "MZ",
        "ST",
        "ET",
        "CIV",
        "CU",
        "CD",
    ],
    "南美": [
        "AR",
        "AI",
        "BO",
        "BR",
        "AG",
        "BS",
        "CL",
        "BB",
        "BZ",
        "BM",
        "CO",
        "KY",
        "EC",
        "GY",
        "CR",
        "DO",
        "GD",
        "PY",
        "SV",
        "JM",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "PE",
        "SR",
        "PR",
        "KN",
        "LC",
        "VC",
        "UY",
        "TT",
        "TC",
        "VE",
    ],
    "南美洲": [
        "AR",
        "AI",
        "BO",
        "BR",
        "AG",
        "BS",
        "CL",
        "BB",
        "BZ",
        "BM",
        "CO",
        "KY",
        "EC",
        "GY",
        "CR",
        "DO",
        "GD",
        "PY",
        "SV",
        "JM",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "PE",
        "SR",
        "PR",
        "KN",
        "LC",
        "VC",
        "UY",
        "TT",
        "TC",
        "VE",
    ],
    "south america": [
        "AR",
        "AI",
        "BO",
        "BR",
        "AG",
        "BS",
        "CL",
        "BB",
        "BZ",
        "BM",
        "CO",
        "KY",
        "EC",
        "GY",
        "CR",
        "DO",
        "GD",
        "PY",
        "SV",
        "JM",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "PE",
        "SR",
        "PR",
        "KN",
        "LC",
        "VC",
        "UY",
        "TT",
        "TC",
        "VE",
    ],
    "拉美": [
        "AR",
        "AI",
        "BO",
        "BR",
        "AG",
        "BS",
        "CL",
        "BB",
        "BZ",
        "BM",
        "CO",
        "KY",
        "EC",
        "GY",
        "CR",
        "DO",
        "GD",
        "PY",
        "SV",
        "JM",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "PE",
        "SR",
        "PR",
        "KN",
        "LC",
        "VC",
        "UY",
        "TT",
        "TC",
        "VE",
    ],
    "latin america": [
        "AR",
        "AI",
        "BO",
        "BR",
        "AG",
        "BS",
        "CL",
        "BB",
        "BZ",
        "BM",
        "CO",
        "KY",
        "EC",
        "GY",
        "CR",
        "DO",
        "GD",
        "PY",
        "SV",
        "JM",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "PE",
        "SR",
        "PR",
        "KN",
        "LC",
        "VC",
        "UY",
        "TT",
        "TC",
        "VE",
    ],
    "latin_america": [
        "AR",
        "AI",
        "BO",
        "BR",
        "AG",
        "BS",
        "CL",
        "BB",
        "BZ",
        "BM",
        "CO",
        "KY",
        "EC",
        "GY",
        "CR",
        "DO",
        "GD",
        "PY",
        "SV",
        "JM",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "PE",
        "SR",
        "PR",
        "KN",
        "LC",
        "VC",
        "UY",
        "TT",
        "TC",
        "VE",
    ],
    "latam": [
        "AR",
        "AI",
        "BO",
        "BR",
        "AG",
        "BS",
        "CL",
        "BB",
        "BZ",
        "BM",
        "CO",
        "KY",
        "EC",
        "GY",
        "CR",
        "DO",
        "GD",
        "PY",
        "SV",
        "JM",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "PE",
        "SR",
        "PR",
        "KN",
        "LC",
        "VC",
        "UY",
        "TT",
        "TC",
        "VE",
    ],
    "中东": [
        "dz",
        "eg",
        "bh",
        "cy",
        "iq",
        "il",
        "jo",
        "kw",
        "lb",
        "tn",
        "om",
        "qa",
        "sa",
        "ae",
        "ye",
        "ly",
        "ma",
        "sy",
        "ir",
    ],
    "middle east": [
        "dz",
        "eg",
        "bh",
        "cy",
        "iq",
        "il",
        "jo",
        "kw",
        "lb",
        "tn",
        "om",
        "qa",
        "sa",
        "ae",
        "ye",
        "ly",
        "ma",
        "sy",
        "ir",
    ],
    "全球": ["global"],
    "global": ["global"],
    "欧美": ["ee", "we", "eur", "na"],
    "海外": ["global_wo_china"],
    "global_wo_china": ["global_wo_china"],
    "global wo china": ["global_wo_china"],
    "overseas": ["global_wo_china"],
    "oversea": ["global_wo_china"],
    "北美": ["us", "ca"],
    "north america": ["us", "ca"],
    "东南亚": ["bn", "kh", "id", "my", "mm", "ph", "sg", "th", "vn"],
    "southeast asia": ["bn", "kh", "id", "my", "mm", "ph", "sg", "th", "vn"],
    "sea": ["bn", "kh", "id", "my", "mm", "ph", "sg", "th", "vn"],
    "southeast_asia": ["bn", "kh", "id", "my", "mm", "ph", "sg", "th", "vn"],
    "ASEAN": ["bn", "kh", "id", "my", "mm", "ph", "sg", "th", "vn"],
    "大洋洲": ["au", "fj", "fm", "nz", "pw", "pg", "sb"],
    "oceania": ["au", "fj", "fm", "nz", "pw", "pg", "sb"],
    "亚洲": ["kr", "jpn", "sea", "chn", "hmt", "in", "other asia"],
    "asia": ["kr", "jpn", "sea", "chn", "hmt", "in", "other asia"],
}

REGION_MAP_FOR_METRICS_QUERY = {
    "其他亚洲": ["other asia"],
    "other asia": ["other asia"],
    "中国": ["chn"],
    "china": ["chn"],
    "mainland china": ["chn"],
    "港澳台": ["hmt"],
    "hmt": ["hmt"],
    "西欧": [
        "we"
    ],
    "west europe": [
        "we"
    ],
    "东欧": [
        "ee"
    ],
    "east europe": [
        "ee"
    ],
    "eastern europe": [
        "ee"
    ],
    "eeu": [
        "ee"
    ],
    "欧洲": ["we", "ee"],
    "europe": ["we", "ee"],
    "非洲": ["af"],
    "africa": [
        "af"
    ],
    "南极洲": ["an"],
    "antarctica": ["an"],
    "南美": ["sa"],
    "南美洲": ["sa"],
    "south america": [
        "sa"],
    "拉美": [
        "sa"
    ],
    "latin america": [
        "sa"
    ],
    "latin_america": [
        "sa"
    ],
    "latam": [
        "sa"
    ],
    "中东": [
        "me"
    ],
    "middle east": [
        "me"
    ],
    # MENA aliases (maps to Middle East in databrain system)
    "mena": ["me"],
    "中东北非": ["me"],
    "中东和北非": ["me"],
    "middle east and north africa": ["me"],
    "middle east & north africa": ["me"],
    "全球": ["global"],
    "global": ["global"],
    "欧美": ["ee", "we", "eur", "na"],
    "海外": ["global_wo_china"],
    "global_wo_china": ["global_wo_china"],
    "global wo china": ["global_wo_china"],
    "overseas": ["global_wo_china"],
    "oversea": ["global_wo_china"],
    "北美": ["na"],
    "north america": ["na"],
    "america": ["na"],
    "americas": ["na", "sa"],
    "东南亚": ["sea"],
    "southeast asia": ["sea"],
    "sea": ["sea"],
    "southeast_asia": ["sea"],
    "ASEAN": ["sea"],
    "大洋洲": ["oa"],
    "oceania": ["oa"],
    "亚洲": ["other asia", "hmt", "in", "kr", "jpn", "sea", "chn"],
    "asia": ["other asia", "hmt", "in", "kr", "jpn", "sea", "chn"],
    # Shorthand aliases for existing region codes
    "jpn": ["jpn"],  # Japan (region-level code used in stream data)
    "jp": ["jpn"],   # Japan shorthand
    "kr": ["kr"],    # South Korea
    "in": ["in"],    # India
    "chn": ["chn"],  # China
    "na": ["na"],    # North America
    "we": ["we"],    # West Europe
    "ee": ["ee"],    # East Europe
    "eur": ["eur"],  # Europe (combined)
    "me": ["me"],    # Middle East
    "sa": ["sa"],    # South America
    "oa": ["oa"],    # Oceania
    "af": ["af"],    # Africa
    "an": ["an"],    # Antarctica
    # 以下为「易写进 regions 的别名」→ 仅指向本表已出现的 metrics region 码（jpn/kr/in/chn 等），不引入 us/gb/id 等未在本表定义的码
    "japan": ["jpn"],
    "日本": ["jpn"],
    "cn": ["chn"],
    "中国大陆": ["chn"],
    "国内": ["chn"],
    "south korea": ["kr"],
    "korea": ["kr"],
    "republic of korea": ["kr"],
    "韩国": ["kr"],
    "대한민국": ["kr"],
    "india": ["in"],
    "印度": ["in"],
}

REGION_MAP_PROFILE = {
    "港澳台": ["tw", "hk", "mo"],
    "china(hk,mo,tw)": ["tw", "hk", "mo"],
    "西欧": [
        "au",
        "be",
        "dk",
        "fi",
        "fr",
        "de",
        "ie",
        "it",
        "lu",
        "nl",
        "no",
        "pt",
        "es",
        "se",
        "ch",
        "gb",
    ],
    "west europe": [
        "au",
        "be",
        "dk",
        "fi",
        "fr",
        "de",
        "ie",
        "it",
        "lu",
        "nl",
        "no",
        "pt",
        "es",
        "se",
        "ch",
        "gb",
    ],
    "东欧": [
        "al",
        "bg",
        "cz",
        "ee",
        "gr",
        "hu",
        "lv",
        "lt",
        "pl",
        "ro",
        "sk",
        "si",
        "ua",
        "rs",
        "me",
        "hr",
        "mk",
        "ba",
        "xk",
        "by",
        "md",
        "ru",
        "kz",
        "am",
        "az",
        "ge",
        "tr",
        "cy",
        "mt",
        "sm",
        "va",
    ],
    "east europe": [
        "al",
        "bg",
        "cz",
        "ee",
        "gr",
        "hu",
        "lv",
        "lt",
        "pl",
        "ro",
        "sk",
        "si",
        "ua",
        "rs",
        "me",
        "hr",
        "mk",
        "ba",
        "xk",
        "by",
        "md",
        "ru",
        "kz",
        "am",
        "az",
        "ge",
        "tr",
        "cy",
        "mt",
        "sm",
        "va",
    ],
    "欧洲": [
        "au",
        "be",
        "dk",
        "fi",
        "fr",
        "de",
        "ie",
        "it",
        "lu",
        "nl",
        "no",
        "pt",
        "es",
        "se",
        "ch",
        "gb",
        "al",
        "bg",
        "cz",
        "ee",
        "gr",
        "hu",
        "lv",
        "lt",
        "pl",
        "ro",
        "sk",
        "si",
        "ua",
        "rs",
        "me",
        "hr",
        "mk",
        "ba",
        "xk",
        "by",
        "md",
        "ru",
        "kz",
        "am",
        "az",
        "ge",
        "tr",
        "cy",
        "mt",
        "sm",
        "va",
    ],
    "europe": [
        "au",
        "be",
        "dk",
        "fi",
        "fr",
        "de",
        "ie",
        "it",
        "lu",
        "nl",
        "no",
        "pt",
        "es",
        "se",
        "ch",
        "gb",
        "al",
        "bg",
        "cz",
        "ee",
        "gr",
        "hu",
        "lv",
        "lt",
        "pl",
        "ro",
        "sk",
        "si",
        "ua",
        "rs",
        "me",
        "hr",
        "mk",
        "ba",
        "xk",
        "by",
        "md",
        "ru",
        "kz",
        "am",
        "az",
        "ge",
        "tr",
        "cy",
        "mt",
        "sm",
        "va",
    ],
    "非洲": [
        "ao",
        "bj",
        "bw",
        "bf",
        "cv",
        "td",
        "cd",
        "gm",
        "gh",
        "gn",
        "gw",
        "ke",
        "lr",
        "mg",
        "mw",
        "ml",
        "mr",
        "mu",
        "mz",
        "na",
        "ne",
        "ng",
        "st",
        "sn",
        "sc",
        "sl",
        "za",
        "sz",
        "tz",
        "ug",
        "zw",
    ],
    "africa": [
        "ao",
        "bj",
        "bw",
        "bf",
        "cv",
        "td",
        "cd",
        "gm",
        "gh",
        "gn",
        "gw",
        "ke",
        "lr",
        "mg",
        "mw",
        "ml",
        "mr",
        "mu",
        "mz",
        "na",
        "ne",
        "ng",
        "st",
        "sn",
        "sc",
        "sl",
        "za",
        "sz",
        "tz",
        "ug",
        "zw",
    ],
    "南美": [
        "ar",
        "bo",
        "br",
        "cl",
        "co",
        "ec",
        "fk",
        "gf",
        "gy",
        "py",
        "pe",
        "sr",
        "uy",
        "ve",
    ],
    "南美洲": [
        "ar",
        "bo",
        "br",
        "cl",
        "co",
        "ec",
        "fk",
        "gf",
        "gy",
        "py",
        "pe",
        "sr",
        "uy",
        "ve",
    ],
    "south america": [
        "ar",
        "bo",
        "br",
        "cl",
        "co",
        "ec",
        "fk",
        "gf",
        "gy",
        "py",
        "pe",
        "sr",
        "uy",
        "ve",
    ],
    "中东": [
        "dz",
        "eg",
        "bh",
        "cy",
        "iq",
        "il",
        "jo",
        "kw",
        "lb",
        "tn",
        "om",
        "qa",
        "sa",
        "ae",
        "ye",
        "ly",
        "ma",
        "sy",
        "ir",
    ],
    "middle east": [
        "dz",
        "eg",
        "bh",
        "cy",
        "iq",
        "il",
        "jo",
        "kw",
        "lb",
        "tn",
        "om",
        "qa",
        "sa",
        "ae",
        "ye",
        "ly",
        "ma",
        "sy",
        "ir",
    ],
    "全球": ["global", "global_wo_china"],
    "global": ["global", "global_wo_china"],
    "欧美": ["ee", "we", "eur", "na"],
    "海外": "global_wo_china",
    "北美": ["us", "ca", "dm", "ms", "vg"],
    "north america": ["us", "ca", "dm", "ms", "vg"],
    "东南亚": ["bn", "kh", "id", "my", "mm", "ph", "sg", "th", "vn"],
    "southeast asia": ["bn", "kh", "id", "my", "mm", "ph", "sg", "th", "vn"],
    "大洋洲": ["au", "fj", "fm", "nz", "pw", "pg", "sb"],
    "oceania": ["au", "fj", "fm", "nz", "pw", "pg", "sb"],
    "亚洲": ["kr", "jp", "cn", "tw", "hk", "mo", "in", "bt", "la", "mn", "lk"],
    "asia": ["kr", "jp", "cn", "tw", "hk", "mo", "in", "bt", "la", "mn", "lk"],
}

COUNTRY_MAP_DASHBOARD = {
    "algeria": "dz",
    "armenia": "am",
    "chad": "td",
    "egypt": "eg",
    "azerbaijan": "az",
    "bahrain": "bh",
    "cyprus": "cy",
    "iraq": "iq",
    "israel": "il",
    "mauritania": "mr",
    "jordan": "jo",
    "kuwait": "kw",
    "lebanon": "lb",
    "tunisia": "tn",
    "oman": "om",
    "qatar": "qa",
    "china(mainland)": "cn",
    "china": "cn",
    "hong kong, china": "hk",
    "hong kong": "hk",
    "macau, china": "mo",
    "macau": "mo",
    "taiwan, china": "tw",
    "taiwan": "tw",
    "saudi arabia": "sa",
    "australia": "au",
    "turkey": "tr",
    "bengal": "bd",
    "bhutan": "bt",
    "botswana": "bw",
    "brunei": "bn",
    "cambodia": "kh",
    "canada": "ca",
    "denmark": "dk",
    "fiji": "fj",
    "estonia": "ee",
    "gambia": "gm",
    "ghana": "gh",
    "albania": "al",
    "argentina": "ar",
    "belarus": "by",
    "finland": "fi",
    "india": "in",
    "iceland": "is",
    "kenya": "ke",
    "indonesia": "id",
    "liberia": "lr",
    "malawi": "mw",
    "laos": "la",
    "croatia": "hr",
    "mauritius": "mu",
    "micronesia": "fm",
    "mongolia": "mn",
    "anguilla": "ai",
    "malaysia": "my",
    "namibia": "na",
    "nepal": "np",
    "austria": "at",
    "new zealand": "nz",
    "nigeria": "ng",
    "ireland": "ie",
    "pakistan": "pk",
    "palau": "pw",
    "papua new guinea": "pg",
    "myanmar": "mm",
    "bulgaria": "bg",
    "czech republic": "cz",
    "sierra leone": "sl",
    "philippines": "ph",
    "solomon islands": "sb",
    "south africa": "za",
    "sri lanka": "lk",
    "swaziland": "sz",
    "latvia": "lv",
    "kazakhstan": "kz",
    "tanzania": "tz",
    "kyrgyzstan": "kg",
    "uganda": "ug",
    "lithuania": "lt",
    "united states": "us",
    "tajikistan": "tj",
    "singapore": "sg",
    "zimbabwe": "zw",
    "belgium": "be",
    "benin": "bj",
    "burkina faso": "bf",
    "congo": "cg",
    "france": "fr",
    "germany": "de",
    "madagascar": "mg",
    "mali": "ml",
    "niger": "ne",
    "senegal": "sn",
    "seychelles": "sc",
    "luxembourg": "lu",
    "netherlands": "nl",
    "switzerland": "ch",
    "thailand": "th",
    "greece": "gr",
    "japan": "jp",
    "south korea": "kr",
    "angola": "ao",
    "bolivia": "bo",
    "cape verde": "cv",
    "guinea-bissau": "gw",
    "mozambique": "mz",
    "italy": "it",
    "sao tome and principe": "st",
    "brazil": "br",
    "malta": "mt",
    "hungary": "hu",
    "moldova": "md",
    "north macedonia": "mk",
    "poland": "pl",
    "norway": "no",
    "turkmenistan": "tm",
    "uzbekistan": "uz",
    "sweden": "se",
    "united kingdom": "gb",
    "portugal": "pt",
    "romania": "ro",
    "russia": "ru",
    "slovakia": "sk",
    "slovenia": "si",
    "ukraine": "ua",
    "antigua and barbuda": "ag",
    "bahamas": "bs",
    "chile": "cl",
    "barbados": "bb",
    "british virgin islands": "vg",
    "belize": "bz",
    "bermuda": "bm",
    "colombia": "co",
    "cayman islands": "ky",
    "dominica": "dm",
    "ecuador": "ec",
    "guyana": "gy",
    "costa rica": "cr",
    "dominican republic": "do",
    "grenada": "gd",
    "paraguay": "py",
    "el salvador": "sv",
    "jamaica": "jm",
    "guatemala": "gt",
    "honduras": "hn",
    "montserrat": "ms",
    "mexico": "mx",
    "nicaragua": "ni",
    "panama": "pa",
    "peru": "pe",
    "suriname": "sr",
    "puerto rico": "pr",
    "spain": "es",
    "st. kitts and nevis": "kn",
    "st. lucia": "lc",
    "st. vincent and the grenadines": "vc",
    "uruguay": "uy",
    "trinidad and tobago": "tt",
    "turks and caicos": "tc",
    "venezuela": "ve",
    "vietnam": "vn",
    "united arab emirates": "ae",
    "yemen": "ye",
    "worldwide": "#n/a",
    "libya": "ly",
    "morocco": "ma",
    "syria": "sy",
    "iran": "ir",
    "georgia": "ge",
    "serbia": "rs",
    "ethiopia": "et",
    "bosnia and herzegovina": "ba",
    "côte d'ivoire": "civ",
    "cuba": "cu",
    "dr congo": "cd",
    "andorra": "ad",
    "liechtenstein": "li",
    "monaco": "mc",
    "country_english name": "country_english abbreviation",
    "country_chinese_name": "country_english abbreviation",
    "阿尔及利亚": "dz",
    "亚美尼亚": "am",
    "乍得": "td",
    "埃及": "eg",
    "阿塞拜疆": "az",
    "巴林": "bh",
    "塞浦路斯": "cy",
    "伊拉克": "iq",
    "以色列": "il",
    "毛里塔尼亚": "mr",
    "约旦": "jo",
    "科威特": "kw",
    "黎巴嫩": "lb",
    "突尼斯": "tn",
    "阿曼": "om",
    "卡塔尔": "qa",
    "中国": "cn",
    "国内": "cn",
    "中国大陆": "cn",
    "中国香港": "hk",
    "香港": "hk",
    "中国澳门": "mo",
    "澳门": "mo",
    "中国台湾": "tw",
    "沙特阿拉伯": "sa",
    "沙特": "sa",
    "澳大利亚": "au",
    "土耳其": "tr",
    "孟加拉": "bd",
    "不丹": "bt",
    "博茨瓦纳": "bw",
    "文莱": "bn",
    "柬埔寨": "kh",
    "加拿大": "ca",
    "丹麦": "dk",
    "斐济": "fj",
    "爱沙尼亚": "ee",
    "冈比亚": "gm",
    "加纳": "gh",
    "uk": "gb",
    "阿尔巴尼亚": "al",
    "阿根廷": "ar",
    "白俄罗斯": "by",
    "芬兰": "fi",
    "印度": "in",
    "冰岛": "is",
    "肯尼亚": "ke",
    "印度尼西亚": "id",
    "利比里亚": "lr",
    "马拉维": "mw",
    "老挝": "la",
    "克罗地亚": "hr",
    "毛里求斯": "mu",
    "密克罗尼西亚联邦": "fm",
    "蒙古": "mn",
    "安圭拉": "ai",
    "马来西亚": "my",
    "纳米比亚": "na",
    "尼泊尔": "np",
    "奥地利": "at",
    "新西兰": "nz",
    "尼日利亚": "ng",
    "爱尔兰": "ie",
    "巴基斯坦": "pk",
    "帕劳": "pw",
    "巴布亚新几内亚": "pg",
    "缅甸": "mm",
    "保加利亚": "bg",
    "捷克": "cz",
    "塞拉利昂": "sl",
    "菲律宾": "ph",
    "所罗门群岛": "sb",
    "南非": "za",
    "斯里兰卡": "lk",
    "斯威士兰": "sz",
    "拉脱维亚": "lv",
    "哈萨克斯坦": "kz",
    "坦桑尼亚": "tz",
    "吉尔吉斯斯坦": "kg",
    "乌干达": "ug",
    "立陶宛": "lt",
    "美国": "us",
    "塔吉克斯坦": "tj",
    "新加坡": "sg",
    "津巴布韦": "zw",
    "比利时": "be",
    "贝宁": "bj",
    "布基纳法索": "bf",
    "刚果（布）": "cg",
    "法国": "fr",
    "德国": "de",
    "马达加斯加": "mg",
    "马里": "ml",
    "尼日尔": "ne",
    "塞内加尔": "sn",
    "塞舌尔": "sc",
    "卢森堡": "lu",
    "荷兰": "nl",
    "瑞士": "ch",
    "泰国": "th",
    "希腊": "gr",
    "日本": "jp",
    "韩国": "kr",
    "安哥拉": "ao",
    "玻利维亚": "bo",
    "佛得角": "cv",
    "几内亚比绍": "gw",
    "莫桑比克": "mz",
    "意大利": "it",
    "圣多美和普林西比": "st",
    "巴西": "br",
    "马耳他": "mt",
    "匈牙利": "hu",
    "摩尔多瓦": "md",
    "马其顿": "mk",
    "波兰": "pl",
    "挪威": "no",
    "土库曼斯坦": "tm",
    "乌兹别克斯坦": "uz",
    "瑞典": "se",
    "英国": "gb",
    "葡萄牙": "pt",
    "罗马尼亚": "ro",
    "俄罗斯": "ru",
    "斯洛伐克": "sk",
    "斯洛文尼亚": "si",
    "乌克兰": "ua",
    "安提瓜和巴布达": "ag",
    "巴哈马": "bs",
    "智利": "cl",
    "巴巴多斯": "bb",
    "英属维尔京群岛": "vg",
    "伯利兹": "bz",
    "百慕大": "bm",
    "哥伦比亚": "co",
    "开曼群岛": "ky",
    "多米尼克": "dm",
    "厄瓜多尔": "ec",
    "圭亚那": "gy",
    "哥斯达黎加": "cr",
    "多米尼加": "do",
    "格林纳达": "gd",
    "巴拉圭": "py",
    "萨尔瓦多": "sv",
    "牙买加": "jm",
    "危地马拉": "gt",
    "洪都拉斯": "hn",
    "蒙特塞拉特": "ms",
    "墨西哥": "mx",
    "尼加拉瓜": "ni",
    "巴拿马": "pa",
    "秘鲁": "pe",
    "苏里南": "sr",
    "波多黎各": "pr",
    "西班牙": "es",
    "圣基茨和尼维斯": "kn",
    "圣卢西亚": "lc",
    "圣文森特和格林纳丁斯": "vc",
    "乌拉圭": "uy",
    "特立尼达和多巴哥": "tt",
    "特克斯和凯科斯群岛": "tc",
    "委内瑞拉": "ve",
    "越南": "vn",
    "阿联酋": "ae",
    "也门": "ye",
    "全球": "#n/a",
    "利比亚": "ly",
    "摩洛哥": "ma",
    "叙利亚": "sy",
    "伊朗": "ir",
    "格鲁吉亚": "ge",
    "塞尔维亚": "rs",
    "埃塞俄比亚": "et",
    "波黑": "ba",
    "科特迪瓦": "civ",
    "古巴": "cu",
    "刚果（金）": "cd",
    "安道尔": "ad",
    "列支敦士登": "li",
    "摩纳哥": "mc",
}

COUNTRY_MAP_INTEL = {
    "global": "global",
    "海外": "global_wo_china",
    "global_wo_china": "global_wo_china",  # 新增：支持原始格式
    "global wo china": "global_wo_china",
    "oversea": "global_wo_china",
    "overseas": "global_wo_china",
    "algeria": "dz",
    "armenia": "am",
    "chad": "td",
    "egypt": "eg",
    "azerbaijan": "az",
    "bahrain": "bh",
    "cyprus": "cy",
    "uk": "gb",
    "iraq": "iq",
    "israel": "il",
    "mauritania": "mr",
    "jordan": "jo",
    "kuwait": "kw",
    "lebanon": "lb",
    "tunisia": "tn",
    "oman": "om",
    "qatar": "qa",
    "china(mainland)": "cn",
    "china": "cn",
    "hong kong, china": "hk",
    "hong kong": "hk",
    "macau, china": "mo",
    "macau": "mo",
    "taiwan, china": "tw",
    "taiwan": "tw",
    "saudi arabia": "sa",
    "australia": "au",
    "turkey": "tr",
    "bengal": "bd",
    "bhutan": "bt",
    "botswana": "bw",
    "brunei": "bn",
    "cambodia": "kh",
    "canada": "ca",
    "denmark": "dk",
    "fiji": "fj",
    "estonia": "ee",
    "gambia": "gm",
    "ghana": "gh",
    "albania": "al",
    "argentina": "ar",
    "belarus": "by",
    "finland": "fi",
    "india": "in",
    "iceland": "is",
    "kenya": "ke",
    "indonesia": "id",
    "liberia": "lr",
    "malawi": "mw",
    "laos": "la",
    "croatia": "hr",
    "mauritius": "mu",
    "micronesia": "fm",
    "mongolia": "mn",
    "anguilla": "ai",
    "malaysia": "my",
    "namibia": "na",
    "nepal": "np",
    "austria": "at",
    "new zealand": "nz",
    "nigeria": "ng",
    "ireland": "ie",
    "pakistan": "pk",
    "palau": "pw",
    "papua new guinea": "pg",
    "myanmar": "mm",
    "bulgaria": "bg",
    "czech republic": "cz",
    "sierra leone": "sl",
    "philippines": "ph",
    "solomon islands": "sb",
    "south africa": "za",
    "sri lanka": "lk",
    "swaziland": "sz",
    "latvia": "lv",
    "kazakhstan": "kz",
    "tanzania": "tz",
    "kyrgyzstan": "kg",
    "uganda": "ug",
    "lithuania": "lt",
    "united states": "us",
    "tajikistan": "tj",
    "singapore": "sg",
    "zimbabwe": "zw",
    "belgium": "be",
    "benin": "bj",
    "burkina faso": "bf",
    "congo": "cg",
    "france": "fr",
    "germany": "de",
    "madagascar": "mg",
    "mali": "ml",
    "niger": "ne",
    "senegal": "sn",
    "seychelles": "sc",
    "luxembourg": "lu",
    "netherlands": "nl",
    "switzerland": "ch",
    "thailand": "th",
    "greece": "gr",
    "japan": "jp",
    "south korea": "kr",
    "angola": "ao",
    "bolivia": "bo",
    "cape verde": "cv",
    "guinea-bissau": "gw",
    "mozambique": "mz",
    "italy": "it",
    "sao tome and principe": "st",
    "brazil": "br",
    "malta": "mt",
    "hungary": "hu",
    "moldova": "md",
    "north macedonia": "mk",
    "poland": "pl",
    "norway": "no",
    "turkmenistan": "tm",
    "uzbekistan": "uz",
    "sweden": "se",
    "united kingdom": "gb",
    "portugal": "pt",
    "romania": "ro",
    "russia": "ru",
    "slovakia": "sk",
    "slovenia": "si",
    "ukraine": "ua",
    "antigua and barbuda": "ag",
    "bahamas": "bs",
    "chile": "cl",
    "barbados": "bb",
    "british virgin islands": "vg",
    "belize": "bz",
    "bermuda": "bm",
    "colombia": "co",
    "cayman islands": "ky",
    "dominica": "dm",
    "ecuador": "ec",
    "guyana": "gy",
    "costa rica": "cr",
    "dominican republic": "do",
    "grenada": "gd",
    "paraguay": "py",
    "el salvador": "sv",
    "jamaica": "jm",
    "guatemala": "gt",
    "honduras": "hn",
    "montserrat": "ms",
    "mexico": "mx",
    "nicaragua": "ni",
    "panama": "pa",
    "peru": "pe",
    "suriname": "sr",
    "puerto rico": "pr",
    "spain": "es",
    "st. kitts and nevis": "kn",
    "st. lucia": "lc",
    "st. vincent and the grenadines": "vc",
    "uruguay": "uy",
    "trinidad and tobago": "tt",
    "turks and caicos": "tc",
    "venezuela": "ve",
    "vietnam": "vn",
    "united arab emirates": "ae",
    "yemen": "ye",
    "worldwide": "#n/a",
    "libya": "ly",
    "morocco": "ma",
    "syria": "sy",
    "iran": "ir",
    "georgia": "ge",
    "serbia": "rs",
    "ethiopia": "et",
    "bosnia and herzegovina": "ba",
    "côte d'ivoire": "civ",
    "cuba": "cu",
    "dr congo": "cd",
    "andorra": "ad",
    "liechtenstein": "li",
    "monaco": "mc",
    "阿尔及利亚": "dz",
    "亚美尼亚": "am",
    "乍得": "td",
    "埃及": "eg",
    "阿塞拜疆": "az",
    "巴林": "bh",
    "塞浦路斯": "cy",
    "伊拉克": "iq",
    "以色列": "il",
    "毛里塔尼亚": "mr",
    "约旦": "jo",
    "科威特": "kw",
    "黎巴嫩": "lb",
    "突尼斯": "tn",
    "阿曼": "om",
    "卡塔尔": "qa",
    "中国": "cn",
    "国内": "cn",
    "中国大陆": "cn",
    "中国香港": "hk",
    "香港": "hk",
    "中国澳门": "mo",
    "澳门": "mo",
    "中国台湾": "tw",
    "沙特阿拉伯": "sa",
    "沙特": "sa",
    "澳大利亚": "au",
    "土耳其": "tr",
    "孟加拉": "bd",
    "不丹": "bt",
    "博茨瓦纳": "bw",
    "文莱": "bn",
    "柬埔寨": "kh",
    "加拿大": "ca",
    "丹麦": "dk",
    "斐济": "fj",
    "爱沙尼亚": "ee",
    "冈比亚": "gm",
    "加纳": "gh",
    "阿尔巴尼亚": "al",
    "阿根廷": "ar",
    "白俄罗斯": "by",
    "芬兰": "fi",
    "印度": "in",
    "冰岛": "is",
    "肯尼亚": "ke",
    "印度尼西亚": "id",
    "利比里亚": "lr",
    "马拉维": "mw",
    "老挝": "la",
    "克罗地亚": "hr",
    "毛里求斯": "mu",
    "密克罗尼西亚联邦": "fm",
    "蒙古": "mn",
    "安圭拉": "ai",
    "马来西亚": "my",
    "纳米比亚": "na",
    "尼泊尔": "np",
    "奥地利": "at",
    "新西兰": "nz",
    "尼日利亚": "ng",
    "爱尔兰": "ie",
    "巴基斯坦": "pk",
    "帕劳": "pw",
    "巴布亚新几内亚": "pg",
    "缅甸": "mm",
    "保加利亚": "bg",
    "捷克": "cz",
    "塞拉利昂": "sl",
    "菲律宾": "ph",
    "所罗门群岛": "sb",
    "南非": "za",
    "斯里兰卡": "lk",
    "斯威士兰": "sz",
    "拉脱维亚": "lv",
    "哈萨克斯坦": "kz",
    "坦桑尼亚": "tz",
    "吉尔吉斯斯坦": "kg",
    "乌干达": "ug",
    "立陶宛": "lt",
    "美国": "us",
    "塔吉克斯坦": "tj",
    "新加坡": "sg",
    "津巴布韦": "zw",
    "比利时": "be",
    "贝宁": "bj",
    "布基纳法索": "bf",
    "刚果（布）": "cg",
    "法国": "fr",
    "德国": "de",
    "马达加斯加": "mg",
    "马里": "ml",
    "尼日尔": "ne",
    "塞内加尔": "sn",
    "塞舌尔": "sc",
    "卢森堡": "lu",
    "荷兰": "nl",
    "瑞士": "ch",
    "泰国": "th",
    "希腊": "gr",
    "日本": "jp",
    "韩国": "kr",
    "安哥拉": "ao",
    "玻利维亚": "bo",
    "佛得角": "cv",
    "几内亚比绍": "gw",
    "莫桑比克": "mz",
    "意大利": "it",
    "圣多美和普林西比": "st",
    "巴西": "br",
    "马耳他": "mt",
    "匈牙利": "hu",
    "摩尔多瓦": "md",
    "马其顿": "mk",
    "波兰": "pl",
    "挪威": "no",
    "土库曼斯坦": "tm",
    "乌兹别克斯坦": "uz",
    "瑞典": "se",
    "英国": "gb",
    "葡萄牙": "pt",
    "罗马尼亚": "ro",
    "俄罗斯": "ru",
    "斯洛伐克": "sk",
    "斯洛文尼亚": "si",
    "乌克兰": "ua",
    "安提瓜和巴布达": "ag",
    "巴哈马": "bs",
    "智利": "cl",
    "巴巴多斯": "bb",
    "英属维尔京群岛": "vg",
    "伯利兹": "bz",
    "百慕大": "bm",
    "哥伦比亚": "co",
    "开曼群岛": "ky",
    "多米尼克": "dm",
    "厄瓜多尔": "ec",
    "圭亚那": "gy",
    "哥斯达黎加": "cr",
    "多米尼加": "do",
    "格林纳达": "gd",
    "巴拉圭": "py",
    "萨尔瓦多": "sv",
    "牙买加": "jm",
    "危地马拉": "gt",
    "洪都拉斯": "hn",
    "蒙特塞拉特": "ms",
    "墨西哥": "mx",
    "尼加拉瓜": "ni",
    "巴拿马": "pa",
    "秘鲁": "pe",
    "苏里南": "sr",
    "波多黎各": "pr",
    "西班牙": "es",
    "圣基茨和尼维斯": "kn",
    "圣卢西亚": "lc",
    "圣文森特和格林纳丁斯": "vc",
    "乌拉圭": "uy",
    "特立尼达和多巴哥": "tt",
    "特克斯和凯科斯群岛": "tc",
    "委内瑞拉": "ve",
    "越南": "vn",
    "阿联酋": "ae",
    "也门": "ye",
    "全球": "#n/a",
    "利比亚": "ly",
    "摩洛哥": "ma",
    "叙利亚": "sy",
    "伊朗": "ir",
    "格鲁吉亚": "ge",
    "塞尔维亚": "rs",
    "埃塞俄比亚": "et",
    "波黑": "ba",
    "科特迪瓦": "civ",
    "古巴": "cu",
    "刚果（金）": "cd",
    "安道尔": "ad",
    "列支敦士登": "li",
    "摩纳哥": "mc",
    "Afghanistan": "af",
    "阿富汗": "af",
    "American Samoa": "as",
    "美属萨摩亚": "as",
    "Aruba": "aw",
    "阿鲁巴": "aw",
    "Burundi": "bi",
    "布隆迪": "bi",
    "Cameroon": "cm",
    "喀麦隆": "cm",
    "Caribisch Nederland": "bq",
    "荷兰加勒比区": "bq",
    "Central African Republic": "cf",
    "中非": "cf",
    "Comoros": "km",
    "科摩罗": "km",
    "Cook Islands": "ck",
    "库克群岛": "ck",
    "Curaçao": "cw",
    "库拉索": "cw",
    "Djibouti": "dj",
    "吉布提": "dj",
    "East Timor": "tl",
    "东帝汶": "tl",
    "Equatorial Guinea": "gq",
    "赤道几内亚": "gq",
    "Eritrea": "er",
    "厄立特里亚": "er",
    "European Union": "eu",
    "欧盟": "eu",
    "Falkland Islands": "fk",
    "福克兰群岛": "fk",
    "Faroe Islands": "fo",
    "法罗群岛": "fo",
    "French Guiana": "gf",
    "法属圭亚那": "gf",
    "French Polynesia": "pf",
    "法属波利尼西亚": "pf",
    "Gabon": "ga",
    "加蓬": "ga",
    "Gibraltar": "gi",
    "直布罗陀": "gi",
    "Greenland": "gl",
    "格陵兰": "gl",
    "Guadeloupe": "gp",
    "瓜德罗普": "gp",
    "Guam": "gu",
    "关岛": "gu",
    "Guernsey": "gg",
    "根西岛": "gg",
    "Guinea": "gn",
    "几内亚": "gn",
    "Haiti": "ht",
    "海地": "ht",
    "Isle of Man": "im",
    "马恩岛": "im",
    "Ivory Coast": "ci",
    "科特迪瓦": "ci",
    "Jersey": "je",
    "泽西岛": "je",
     "基里巴斯": "ki",
    "Kiribati": "ki",
    "科索沃": "xk",
    "Kosovo": "xk",
    "莱索托": "ls",
    "Lesotho": "ls",
    "马尔代夫": "mv",
    "Maldives": "mv",
    "马绍尔群岛": "mh",
    "Marshall Islands": "mh",
    "马提尼克": "mq",
    "Martinique": "mq",
    "马约特": "yt",
    "Mayotte": "yt",
    "黑山": "me",
    "Montenegro": "me",
    "瑙鲁": "nr",
    "Nauru": "nr",
    "新喀里多尼亚": "nc",
    "New Caledonia": "nc",
    "纽埃": "nu",
    "Niue": "nu",
    "诺福克岛": "nf",
    "Norfolk Island": "nf",
    "北马里亚纳群岛": "mp",
    "Northern Mariana Islands": "mp",
    "巴勒斯坦": "ps",
    "Palestine": "ps",
    "卢旺达": "rw",
    "Rwanda": "rw",
    "留尼汪": "re",
    "Réunion": "re",
    "圣巴泰勒米": "bl",
    "Saint Barthélemy": "bl",
    "法属圣马丁": "mf",
    "Saint Martin": "mf",
    "圣皮埃尔和密克隆": "pm",
    "Saint Pierre and Miquelon": "pm",
    "萨摩亚": "ws",
    "Samoa": "ws",
    "圣马力诺": "sm",
    "San Marino": "sm",
    "荷属圣马丁": "sx",
    "Sint Maarten": "sx",
    "索马里": "so",
    "Somalia": "so",
    "南苏丹": "ss",
    "South Sudan": "ss",
    "苏丹": "sd",
    "Sudan": "sd",
    "多哥": "tg",
    "Togo": "tg",
    "托克劳": "tk",
    "Tokelau": "tk",
    "汤加": "to",
    "Tonga": "to",
    "图瓦卢": "tv",
    "Tuvalu": "tv",
    "美属维尔京群岛": "vi",
    "U.S. Virgin Islands": "vi",
    "乌拉圭": "uy",
    "Uruguay": "uy",
    "瓦努阿图": "vu",
    "Vanuatu": "vu",
    "梵蒂冈": "va",
    "Vatican City": "va",
    "瓦利斯和富图纳": "wf",
    "Wallis and Futuna": "wf",
    "南斯拉夫": "yu",
    "Yugoslavia": "yu",
    "赞比亚": "zm",
    "Zambia": "zm",
    "奥兰群岛": "ax",
    "Åland Islands": "ax"
}
