ROBLOX_LISTS = [
"(LEO UPDATE + CARS!) Greenville",
"(leo update + cars!) greenville",
"(lil update) tha bronx 3",
"(trick retreat)loomian legacy",
"(🎭Trick Retreat🎃)Loomian Legacy",
"(🐍LIL UPDATE🐍) THA BRONX 3🐍",
"+1 Speed Brainrot Escape",
"+1 Speed Per RNG🎲",
"+1 speed 99 nights forest escape",
"+1 speed brainrot escape",
"+1 speed maze",
"+1 speed per rng",
"+1 speed prison escape",
"000 jump rope",
"000 stairs",
"096 [scp]",
"100 Player Floor Is LAVA! 🔥",
"100 Players Musical Chairs",
"100 player floor is lava!",
"100 players musical chairs",
"2 Player Battle Tycoon",
"2 Player Hugs RP",
"2 player battle tycoon",
"2 player hugs rp",
"24 Hours in Elevator...",
"24 hours in elevator...",
"67 clicker!",
"7 DAYS TO LIVE",
"99 Nights in the Bunker🐻 [FURNISH THE BUNKER]",
"99 Nights in the Forest",
"99 Nights in the Forest Tycoon 🔦",
"99 nights in the bunker",
"99 nights in the forest tycoon",
"99 nights in the jungle",
"A Lion's Pride Beta - Lion RP 🦁",
"A Long Road - BETA",
"A desrt [SANDBOX]",
"ABA",
"Ability Wars",
"Absolvement [ALPHA]",
"All Star Tower Defense X",
"Animal Sim: Underwater",
"Animal Topia 🏠 RP",
"Anime Card Clash",
"Anime Fruits [ONE-PUNCH MAN💥]",
"Anime Raid[New World]",
"Answer or Die",
"Apocalypse Rising 2",
"Archived",
"Are You Smart? 🤓",
"Arm Battles💪",
"Arm Wrestle Simulator",
"Army Roads 🚂",
"Arsenal",
"Attack on Titan Revolution",
"Avatar Simulator",
"BAD CAT",
"BARRY'S PRISON RUN! (OBBY)",
"BEYBLADE X-BATTLES [Beta3.0]",
"Baddies 💅",
"Basically FNF: Remix",
"Bathroom Attack",
"Be Fish",
"Be a Beggar!",
"Be a Hole",
"Be a Nurse",
"BedFight ⚔️",
"BedWars [🎃HALLOWEEN]",
"Bee Swarm Simulator",
"Beeface!",
"Ben 10 Super Hero Time",
"Bendy and the ink Machine",
"Berry Avenue 🏠 RP",
"Better Avatar? 👕",
"Better Food? 🍔",
"Blackhawk Rescue Mission 5",
"Blade Ball",
"Blast Zone",
"BlockSpin 🔪 [TURBOLIN]",
"Blocks n' Props",
"Blox Fruits",
"Bloxy Bingo",
"Bomber Squadron [HALLOWEEN]",
"Booga Booga 🌴",
"Boxing Beta! 🥊",
"Brainrot Classic Evolution",
"Brainrot Evolution",
"Brainrot Jenga Tower!",
"Brainrot Jumping",
"Brainrot VS Mecha [Espressona Signora]",
"Break In (Story)",
"Break In 2 (Story)",
"Break In Simulator",
"Break your Bones",
"Bridge Battles!",
"Broken Bones IV - Ragdoll Sim",
"Brookhaven 🏡RP",
"Bubu Thieves 🐻",
"Build & Survive",
"Build A Boat For Treasure",
"Build Defense🛡️",
"Build a Haven",
"Build a Tractor 🚜",
"Build to Survive MONSTERS!",
"Build to Survive 🛠️ [TESTING]",
"Build to Survive!",
"Build with Friends",
"Build, Fight, Steal! (Beta)",
"CAR CRASH🚗",
"CRAZY CHEFS! 👨‍🍳",
"Cage Fishing 🐟",
"Camo Troll Tower 🎨",
"Capybara Evolution",
"Car Driving Indonesia",
"Carros Rebaixados BR (Pre-Alpha)",
"Carry Puzzles (Teamwork Obby)",
"Carry an Egg [2 Player Obby]",
"Cat VS Mouse 🐁",
"Catalog Avatar Creator",
"Catwalk Show",
"Chained Together [2-3-4-5 PLAYER]",
"Chained [2 Player Obby]",
"Chaos Jenga",
"Cheese Escape [Horror]",
"Chicken Jockey [2 Player Obby]",
"Claw Machine Arcade!",
"Clicky Keyboard Tower",
"Climb 1000 Stairs",
"Climb and Jump Tower [🧱LEGO® HAUNTED TOWER]",
"Clip It 😂🎬👗",
"Clone Engine",
"Clone Kingdom Tycoon [NEW!] ⚔️",
"Collect All Pets!",
"Color Block",
"Color or Die 🎨",
"Combat Arena",
"Combat Warriors",
"Conquer The World [🏆NEW UI] WW2",
"Control Europe",
"Convince the CRAZY maid to let you FREE [UPD 1.4]",
"Cook Burgers",
"Cook Pizzas",
"Counter Blox",
"Countryball World 🌎",
"Cozy Small Park 🌳",
"Create a Cart Ride!",
"Criminal Tycoon",
"Croydon: London Bus Simulator",
"DANGEROUS NIGHT [FURNISH THE BUNKER]",
"DON'T GET ELIMINATED",
"DOORS 👁️",
"DUMP [ALPHA]",
"Da Hood",
"Dangerous Horse Riding",
"Dead Rails [HALLOWEEN!]",
"Dead Sewers[🤡Clown Event!][Alpha]",
"Death Penalty",
"Deepwoken: Duskguard",
"Demon Soul Simulator",
"Demonology🕯️",
"Die of Death",
"Dig the Backyard [Alpha]",
"Disaster Island 🏝️ Survival",
"Dog Walk 🐶 [2 Player Obby]",
"Don't Get Crushed By a Giant Rock 🪨",
"Don't Wake the Brainrots!",
"Don't Wake the Fish! 🐟",
"Don't leave the circle! ⭕️",
"Donate Game 💸",
"Doodle Obby ✏️",
"Draw & Switch",
"Draw Me! 🎨",
"Dreamville 🏡 RP [Victorian House]",
"Drive World 🏎️ Drifting & Racing",
"Driving Empire🏎️ Car Racing",
"DronePoint [SAM + DRONE REWORK]",
"Dudes Battlegrounds",
"Dungeon Quest! ⚔️ RPG Adventure",
"ENTRENCHED WW1 🥀",
"ESCAPE EVIL GRANDPA! (OBBY)",
"Easy Glass Bridge (Possible Squid Game)",
"Easy Obby",
"Eat Blobs Simulator",
"Eat the World",
"El Gato Tower 😸 [MEGA UPDATE]",
"Elemental Powers Tycoon",
"Elevator of Fun [🎃]",
"Emergency Emden",
"Emergency Hamburg",
"Escape Angry Head",
"Escape Papa Pizza's Pizzeria! (SCARY OBBY)",
"Escape Running Head",
"Escape The Carnival of Terror Obby!",
"Escape The Lava 🔥",
"Escape The Tsunami 🌊",
"Eternal Towers of Hell",
"Evade",
"FORTLINE",
"FPE:S [🎃]",
"Fast Food Simulator",
"Feather Family 🎃 [Caracara]",
"Feed Your Pet!",
"Field Trip Z",
"Find the Brainrot [215]",
"Find the Markers (320)",
"Fisch 🎃 [FISCHFRIGHT]",
"Fish Go🦈",
"Five Nights TD 2 [RELEASE]",
"Flee the Facility",
"Fling A Friend! [2 Player Obby]",
"Fling Things and People",
"Football Fusion 2",
"Formula Apex Racing",
"Free UGC Obby (AFK or Play)",
"Funk Tower X 💥",
"Funky Friday",
"GREAT SCHOOL BREAKOUT! (First Person Obby)",
"GRUMPY GRAN! (SCARY OBBY)",
"Gacha Online ✨ RP",
"Gardeners Trading Plaza",
"Generic Cooking Game [BETA][UPD2.18.2]",
"German Voice",
"Giga Mansion Tycoon 🏝️",
"Glide Tower",
"Gorilla Tag Ultra",
"Grave/Digger",
"Ground War",
"Growing Up 🎃👻🧹",
"Guess Italian Brainrot or Die 🔊",
"Guide The Bacons",
"Gun Armory Tycoon",
"Gunfight Arena",
"Gunung YNTKTS [HALLOWEEN🎃]",
"Guts & Blackpowder",
"Gym Showdown Simulator",
"HOW TO TRAIN YOUR DRAGON",
"Halloween Obby!",
"Hamood Habibi Tower 🎵",
"Happy Land 🏡RP",
"Harbor East",
"HarmonyTown RP",
"Hello Neighbor [3 Acts]",
"Hero Brawl",
"Hide and Seek Extreme",
"Hide the body🎃",
"Highland Park 🏡RP",
"Hood Wars",
"Horse RNG 🐎",
"House Tycoon 2",
"Hungry Pig🎃",
"Hutan [Voice Chat]",
"I WANNA RUN AWAY TOWER",
"I Wanna Test The Game (Beta Test)",
"INSANE Troll Slap Tower 😈",
"IQ 0 Jump Rope Glass Bridge 🧠",
"IQ Test 🧠",
"Impostor | Among us",
"In Area 51 [ALPHA] [🎃]",
"Indo Hangout",
"Industrialist",
"Infectious Smile",
"Ink Game",
"Insane Elevator!",
"Insomnia [Horror]",
"Islands 👩‍🌾",
"Isles of Ravos 🐲",
"Italian Brainrot Jump Clicker 🧠🚀",
"Italian Brainrot Speed Clicker 🧠⚡",
"Italian Brainrot Thieves 🧠",
"JOODPAKJAI 🎙️",
"Jump Clicker 🚀",
"Jump Showdown",
"Just Build!",
"KPop Demon Hunters Speed Clicker 🎤⚡",
"Kick The Baby [2 Player Obby]",
"Killer Stairs",
"Kitten Game 🐾",
"LOCOfficial!",
"Lasso Animals🤠",
"Last Run",
"Legends Battlegrounds",
"Legends Of Speed ⚡",
"Lethal Ape (forest update)",
"LewisLife 🏡 RP",
"LifeTogether 🏠 RP",
"Like or Dislike",
"Livetopia 🏡 RP",
"Lootify",
"Lucky Avatars! [Outfits Catalog]",
"Lucky Block Tower",
"MIC UP 🔊",
"MUGEN",
"Make a Army! ⚔️",
"Makeup Store Simulator",
"Mansion Tycoon 🌴🏠",
"Marvel and DC Super Heroes",
"Math Murder",
"Math Tower Race",
"Mega Princess Tycoon",
"Merge Tower Defense - UPD 6.0",
"Mermaid Testing 🥭",
"Metro Life 🏡 City RP",
"Mingle Practice (VAMPIRE PART 1) [Ink Game]",
"Morph World! [🌑MOON WOKE UP!!]",
"Mr.Mix",
"Murder Mystery 2",
"Murderers vs Sheriffs 2",
"Murderers vs. Sheriffs",
"Musical Chairs 🎵🪑",
"My Brainrot Egg Farm",
"NFT Battle",
"Natural Disaster Survival",
"Naval Warfare",
"Neighbors 🔊 [17+]",
"NewSmith 🏡 RP",
"Night Shift at Paulie's 🎃 (Early Beta) [HORROR]",
"Nitro Car",
"Noob Army Tycoon ⚔️",
"Noobs in Combat [v5.8]",
"ONE BLOCK",
"Obby Creator",
"Off-Roading Epic",
"Ohio. [🎃CODE HALLOWEEN]",
"Omnidroids Test",
"Ophelia [HORROR]",
"Outcome Memories v0.1",
"PET PARTY 🎉 RP",
"PETAPETA [Chapter2]",
"PETAPETA: School of Nightmares",
"PETS GO! ✨",
"PLAY OR DIE",
"Paradise 🏠 RP",
"Pass or Die 💣",
"Penthouse Tycoon 🗽 [UPDATE]",
"Pet Simulator X! 🐾",
"Pet Story 🐶",
"Phantom Forces",
"Piggy [NEW SKINS + SAFE PLACE REVAMP]",
"Pilfering Pirates",
"Pilot Training Flight Simulator",
"Pixel Blade [QUESTS!]",
"Podiums VC 🔊",
"Pressure",
"Prison Life",
"Prison Pump",
"Project Delta",
"Pull a Sword",
"Pummu Talladega (2024 GEN 7 SOFT BODY)",
"Punch Wall",
"RED BALL 4! [BOSS 2 UPDATE!]",
"RIVALS",
"ROBLOX Rally Racing",
"Racer Vs Police AI",
"Rainbow Friends",
"Raise Animals",
"Realistic Hand RP 🖐🤏 Without VR",
"Realistic Street Soccer",
"Redcliff City 🏡RP",
"Regretevator [ ELEVATOR SIMULATOR ]",
"Rensselaer County",
"Resort Tycoon 2 🌴",
"Restaurant Tycoon 2",
"Retail Tycoon 2",
"Ride A Cart Down A Slide",
"Rise of Nations",
"RoCitizens 🎃",
"Rob the House",
"Roblox_Egor Game",
"Roller Skate OBBY",
"Rope Battles[🎃Halloween🎃]",
"Royale👑High",
"Run Hide Fight",
"SCP Games and SCP Monsters",
"SCP: Roleplay",
"ST : Blockade Battlefront",
"STEAL COOKIES🍪",
"Saber Showdown",
"Salon Makeover 💅",
"Salon de Fiestas",
"Scary Sushi [CHAPTER 2]",
"Seaside RP🏡🌴 City RP",
"Secret Killer",
"Secret Staycation",
"Shindo Life [242]",
"Short Creepy Horror Stories",
"Short Horror Games",
"Shrink Hide & Seek",
"Silent Mansion [HORROR]",
"Silly Simon Says",
"SkyWars [SEASON 3!] ✨",
"Slap Tower 4 🖐️",
"Slap Tower 99 🖐️",
"Snake Simulator",
"Sol's RNG [Halloween🎃]",
"South Bronx: The Trenches 🎃",
"Speed Clicker ⚡",
"Speed Run 4",
"Spider",
"SpongeBob Tower Defense🍍",
"Spray Paint!",
"Squid Game Tower 👀",
"Squid Game [S3]",
"Steal Brainrots Trading Plaza 🛒",
"Steal a Clown",
"Steal a drawn brainrot",
"Stick Battles 🍢",
"Strongman Simulator",
"Super Hero Tycoon",
"Supermarket Simulator",
"Supermarket Together",
"Survive Overnight in a School [FURNISH YOUR DORM]",
"Survive and Kill the Killers in Area 51 !!!",
"Survive on a Raft [🛠️]",
"TPS Street Soccer 🏆",
"TYPE://SOUL",
"Taxi Boss 🚖",
"Team School Breakout! (TEAMWORK OBBY)",
"Team Soccer (3 vs. 3)",
"Teamwork Obby",
"Teamwork Puzzles (Obby)",
"Teamwork Puzzles 2 (Obby)",
"Teddy [CHAPTER 5]",
"The $1,000,000 Jump Rope",
"The Battle Bricks",
"The Corner 🔊",
"The Difficulty Upgrade Tree: Regrown",
"The Dropper ✨ [130+ LEVELS!]",
"The Floor Is LAVA!🔥",
"The Highest Ever Waterslide Obby",
"The Logo Quiz! ⭐ [43]",
"The Mimic 🎃",
"The Powder Box (All Ages)",
"The Presentation Experience",
"The Strongest Battlegrounds",
"The Survival Game",
"The Wild West",
"Theme Park Tycoon 2",
"Timebomb Duels [Alpha]",
"Together [Party Game]",
"Total Roblox Drama",
"Touch Football",
"Touch Soccer",
"Tower Defense X: BETA",
"Tower of Coffee (Coffee Tower)",
"Tower of Hell",
"Tower of Zombies 🧟",
"Trade a Brainrot",
"Train Dog to Fight 🎃⚔️",
"Train to Fight [UPD]",
"Try To Die 💀",
"Twisted [BETA]",
"Ultimate Battlegrounds",
"Ultimate Mining Tycoon - 💾 Update!",
"Ultra Toilet Roleplay 2 [UTTVM]",
"Unbox a 99 Nights in the Forest 🔦📦",
"Underground War 2.0 ⚔️ [NUKE]",
"Valley Prison",
"Violence District",
"Voxels Legacy",
"Wacky Wizards",
"Wall Hop Practice",
"War Machines",
"Warrior Cats: Ultimate Edition",
"Webbed! [2 Player Obby]",
"Westbound",
"Where's Santa [Story]",
"Wizard West",
"World // Zero ⚔️ Anime RPG",
"World of Stands",
"Youtuber Tycoon! [NEW UPDATE]",
"ZOO or OOF🎯",
"Zombie Merge Tycoon",
"Zombie Tycoon",
"Zombie Uprising 🎃",
"Zombie game [upd3]",
"Zooo",
"[ 67🏀 ] Brainrot Battlegrounds",
"[ Ocean Floor🌊] Swordburst 2",
"[2x EXP] Asylum Life 🔊",
"[2x XP]🃏 Borderland",
"[2x💰] Kick a Brainrot",
"[5.6] Demonfall",
"[5700 stage!! ] Effortless Tower",
"[5V5⭐] BATHE DA BABY",
"[5X SPEED] Skibi Defense",
"[67] Catch and Feed a Brainrot!",
"[ADVANCE + KOEI] Asura",
"[ANGKUT] Yahayuk Mount V.02",
"[Aizen] Sakura Stand",
"[BETA] Randomizer: Redux",
"[CAR RACE] DriveX",
"[CARS] Dealership Tycoon 🏎️",
"[CUSTOM PLATES] Fix It Up!",
"[Claymore] War Tycoon",
"[DRILL] untitled boxing game 🥊",
"[DUELS] Murderers VS Sheriffs",
"[EVENT] 🎃 Dragon Adventures 🐉",
"[Evolve] Endless Horde",
"[FALL 🍂] Emergency Response: Liberty County",
"[FIX!] Mount Atin",
"[FPS] Gun Grounds FFA",
"[FREE ADMIN]",
"[FREE KJ] Mystic Battleground",
"[Five Nights At Freddy's] FNAF: Co-op",
"[GIGAN+QOL UPD] Age of Titans",
"[GOLDEN ⭐| TAKEDOWN 😈] Ragdoll Engine",
"[HALLOWEEN EVENT] Marvel Omega",
"[HALLOWEEN] Armless Detective",
"[HALLOWEEN] Dragon Ball Rage",
"[HALLOWEEN] IT GIRL 🎃",
"[Halloween 🎃] Dragon Blox",
"[Halloween] Forgotten Worlds",
"[Halloween] Horse World",
"[Halloween] Pillar Chase 2",
"[IMPACT] Fruit Battlegrounds",
"[KARTING] Southwest Florida Beta",
"[LAKE!]Mount Daun",
"[MTC] Multicrew Tank Combat",
"[MULTIPLE CARRY] 🗻 Mount Sibuatan",
"[NEW SEASON] Light Game",
"[NEW UGC] Untitled Fling Game",
"[NEW!] Sprunki Plus",
"[NEW] Build a Roller Coaster🎢",
"[NEW] Keys 🗝️ Season 24",
"[NEW] Miraculous™ RP: Ladybug & Cat Noir",
"[NEW] Scribble Showdown",
"[NEW] Skateboard of Hell Obby",
"[New Car!🔥] Car Crushers 2 - Physics Simulation",
"[PARRYING] Untitled Forsaken Engine",
"[PUPPET MASTER] Jujutsu Shenanigans",
"[QOL Update!] Midnight Racing: Tokyo",
"[QUESTS!]🚗Midnight Chasers: Highway Racing",
"[REBIRTH+DREX] Jurassic Blocky",
"[RELAPSE] Are you lonely?",
"[RELAPSE] Are you okay?",
"[ROBOT] BEAT BOUNCE 🎶 (GEOMETRY DASH)",
"[SHINJI] DUMMY COUNTER YOUR FRIENDS",
"[SPIRIT] Anime Evolution",
"[SPREAD THE LOVE] Grace",
"[SUMMIT x50] Gunung pedaunan",
"[Skeleton King] Clashers Royale",
"[Sound]Slayer Battlegrounds",
"[The Clique] 💃TOD",
"[UPD 0.5] Invincible Showdown",
"[UPD 6] 🦠 Parasite.exe",
"[UPD 🦇 ] Gym League",
"[UPD!] Italian Brainrot Quiz 🔊",
"[UPD5☁️] Weak Legacy 2",
"[UPDATE 4] Meme Sea",
"[UPDATE!] Gunung Mono",
"[UPDATE!] Toilet World Roleplay 2",
"[UPDATE] BUCKSHOT",
"[UPDATE] M.E.G. Endless Reality",
"[UPDATE] War of the Worlds",
"[UPD] Basketball: Zero",
"[UPD] Bike of Hell",
"[UPD] Build a Brainrot Factory",
"[UPD] Codename: Redux",
"[UPD] Dangerous ATV Driving",
"[UPD] Noob Wars💥!",
"[UPD] Poison Drinks",
"[UPD] Sail and Sink Simulator! [REALISTIC]",
"[UPD] Snowboard Obby ❄ World 8",
"[UPD] Speed Draw!",
"[UPD] Volleyball Legends",
"[UPD] Weapon Fighting Simulator",
"[UPD] Zombies vs Humans",
"[UPD]💀 RIP BRAINROT",
"[UPD]💪Ninja Challenge [Beta]",
"[UPD🃏] something evil will happen",
"[UPD🎃] +1 Speed Prison Escape⚡",
"[UPD🚨] Arrest Brainrot",
"[UPD🦉] +1 Speed 99 Nights Forest Escape",
"[Update 1.5🎆🥶] Project Slayers",
"[Update 9.0] Anime Rangers X",
"[V17] +1 Speed Maze",
"[V2.0] Polish Car Driving",
"[V2.2] Stepford County Railway 🚉",
"[V5] Blox Loot",
"[VC] Podcasts 🎃",
"[W10] Rope Swing Obby",
"[W45] Skateboard Obby",
"[W77] Obby But You’re On a Bike",
"[ZOMBIES!!!] Weird Gun Game",
"[scp] task force",
"[⏰] Horse Race 🐎 [Race Offline]",
"[☠️] Steal A Fish!",
"[☢️] Build a Bunker!",
"[♨️] NEOHEE HOT SPRING",
"[⚒️ QOL + FIXES] Rogue Demon",
"[⚒️ QOL ✨DAILIES + SERAPHIM V2 🪐 ] ONE FRUIT",
"[⚒️] Survive Overnight in a Mega Store",
"[⚖️TRIAL] My Prison",
"[⚙️] CAR BATTLES",
"[⛈️UPD 9] King Legacy",
"[✋] Gear Slap Tower",
"[✨] Rebirth Champions: Ultimate",
"[❄️UPD 16 + CSM 2🩸] Anime Guardians",
"[⭐] K-POP Demon Hunter Evolution",
"[🌀] Bloodlines",
"[🌊] Raise Animals",
"[🌌] 67 Clicker! 🥭",
"[🌌] Shred a Brainrot",
"[🌎W3] Obby But You're Cursed",
"[🌐 QOL 🌐] Azure Latch",
"[🌙 UPDATE] Slap Battles👏",
"[🌞] Steal a Phone📱",
"[🌱] Grass Incremental",
"[🌶️] Car Suspension Test",
"[🌸SZN2] NFL Universe Football",
"[🌹EMPEROR REVAMP] Project Egoist",
"[🌹PLANT] Jujutsu Infinite",
"[🌺]Build An Island! 🏝️",
"[🍀PITY] Ink Game",
"[🍓COSY] Club Roblox RP 💗",
"[🎃 HALLOWEEN] My Racing Track",
"[🎃 NEW MAP!] Kpop Demon Hunters RP",
"[🎃EVENT] Indo Voice",
"[🎃EVENT] Prospecting! 💎",
"[🎃EVENT] Vesteria 👻",
"[🎃HALLOWEEN] Anime Crusaders",
"[🎃HALLOWEEN] Dress To Impress⭐",
"[🎃HALLOWEEN] Primal Pursuit 🦖",
"[🎃HALLOWEEN] Sonic Speed Simulator",
"[🎃HALLOWEEN🍬] Grand Piece Online",
"[🎃Halloween] Anime Eternal",
"[🎃Halloween] Hunty Zombie",
"[🎃NIGHT 1] Tower Defense Simulator",
"[🎃PART 3] Arise Crossover",
"[🎃SZN 3] Arcade Basketball 👻",
"[🎃UPD] Destroy Grandma",
"[🎃UPD] Fish It! 🐟",
"[🎃UPD] Fly a Jetpack 🚀",
"[🎃UPD] Prisoner Life",
"[🎃] 99 Nights in the Forest 🔦",
"[🎃] Bayside High School 🍎",
"[🎃] Blue Lock: Rivals",
"[🎃] Boxywood 🏠 RP",
"[🎃] Brainrot Training",
"[🎃] Build A Cart",
"[🎃] Build to Survive 🛠️",
"[🎃] Color Art: Coloring Games",
"[🎃] Container RNG 📦",
"[🎃] Crush for Brainrots",
"[🎃] DUEL Warriors",
"[🎃] Death Ball",
"[🎃] Dino Bro Tower",
"[🎃] Dubai RP 🏡",
"[🎃] Easy Size Obby",
"[🎃] Epic Minigames 👻",
"[🎃] Fallen Survival🏹",
"[🎃] Fear Elevator 😨",
"[🎃] Garden Tower Defense 🌻",
"[🎃] Gym Star Simulator",
"[🎃] Hunting Season [BETA]",
"[🎃] Imposters & Roles | Among us",
"[🎃] Infinite Tower Tycoon",
"[🎃] Invisible Hide and Seek",
"[🎃] Kite Combat 🪁",
"[🎃] Maple Hospital 🍂",
"[🎃] Meet People Across The World 🔊",
"[🎃] Mega Hide and Seek!",
"[🎃] Military Tycoon ®",
"[🎃] Neighbors 🔊",
"[🎃] Notoriety: A PAYDAY® Experience",
"[🎃] Obby but you have long arms",
"[🎃] PLS DONATE 💸",
"[🎃] Plane Training✈️",
"[🎃] Protect The House From Monsters",
"[🎃] Racket Rivals",
"[🎃] SHARP",
"[🎃] Shoot a Brainrot!",
"[🎃] Slap Tower 🖐️",
"[🎃] Street Life Remastered",
"[🎃] The Apocalypse",
"[🎃] Twilight Daycare!✨RP",
"[🎃] Voxel Sandbox 🔨",
"[🎃] Welcome to Bloxburg",
"[🎃] Your Goblin Mine! 💰",
"[🎃] ZO SAMURAI SWORD FIGHTING",
"[🎃] build ur base ⚔️",
"[🎃] ⚔️Dungeon RNG",
"[🎃] 🏭 Factory RNG",
"[🎃]Cut Trees",
"[🎃]Tokyo Claw Machine",
"[🎃💀🎃] Brainrot Tower Defense",
"[🎉RELEASE] GHOST: Samurai Fighting",
"[🎉SODA POP] Sing It! Karaoke Battles [VC🎤]",
"[🎲] Unboxing RNG!",
"[🎶HALLOWEEN MIKUNA + 4X] Anime Spirits",
"[🏆FIFA] Super League Soccer!",
"[🏎️UPD] Vehicle Legends 🏎️ Cars!",
"[🏝️ESCAPE] Squid Game X",
"[🏝️] GO FISHING 🐟",
"[🏭] My Tycoon!",
"[🐂] Savannah Life",
"[🐉Pets][V42]Cultivation: Mortal to Immortal",
"[🐟 MAP] NPC or DIE!💢",
"[🐦 MOVES] Heroes Battlegrounds",
"[🐱] Color Game! 🎨",
"[🐲] MOUNT RNG",
"[🐴] Horse Valley",
"[🐺 WEREWOLF KAKUJA REWORKED!] Ro-Ghoul [ALPHA]",
"[👁️] Brainrot Zombie Evolution",
"[👊YAKUZA] A Universal Time 5.3",
"[👋] Steal a Slap!",
"[👗] Barbie DreamHouse Tycoon",
"[👹 Episode 79 Part 2] Toilet Tower Defense",
"[👹 Tokyo Ghoul + QoL 🪦] Anime Last Stand",
"[👻] Adopt Me!",
"[👻] Farming and Friends",
"[👻] Grow a Garden 🌶️",
"[👻] Saber Simulator",
"[👻] Yeet A Friend!",
"[👻🍂] Wild Horse Islands",
"[💀] Banana Eats",
"[💀] Elimination",
"[💜250+] Pilchero Outfits",
"[💢 8.5 💢] Anime Vanguards",
"[💥] Jujutsu Beatdown",
"[💰🍀]⚽Goal Kick Simulator",
"[📜] Granny",
"[📦] Steal A Phone",
"[🔥SKATEPARK] MX WORLD",
"[🔥] FLASHPOINT⚡",
"[🔪] Forsaken",
"[🗡️] Criminality",
"[🗺️New World] Brainrot +1 Power",
"[🗺️] GEF",
"[🗺️] Plants Vs Brainrots 🌻",
"[😈INSANE!] Mount Sumbing",
"[🚂] Cart Ride",
"[🚗] Repair a Car",
"[🛋️] Survive Overnight in a Bunker",
"[🤩] Champions: Summon Your Team",
"[🥓INCIDENT] The Noob Experiment Battlefront",
"[🥕] Restaurant Tycoon 3",
"[🦈 SHARK] Project Smash",
"[🦉] Steal a Brainrot",
"[🦕 DINO] Zoo Tycoon",
"[🪂] Fruit Forager🍎",
"[🫸🫳🫸🫳] American Plains Mudding",
"a 0ne piece game",
"a bizarre day",
"a bizarre world",
"a desrt",
"a dusty trip",
"a dusty trip [🎃HALLOWEEN]",
"a hero's destiny",
"a lion's pride beta - lion rp",
"a long hike",
"a long hike [Alpha]",
"a long road - beta",
"a stereotypical obby",
"a typical neighborhood",
"a universal time",
"a universal time 5.3",
"a wolf or other",
"a wolf or other ",
"aba",
"ability wars",
"absolvement",
"abyss world",
"action!",
"adopt me",
"adopt me!",
"adventure forward 2",
"aeronautica",
"after the flash: mirage",
"after the flash: wintertide",
"aftermath",
"age of titans",
"aimblox",
"air force simulator",
"aircraft carrier",
"airplane",
"airplane ",
"airplane 2",
"airplane 2",
"airplane 3",
"airplane 3",
"airplane 4",
"airplane 4",
"airplane simulator",
"airport tycoon!",
"airship assault",
"all of us are dead",
"all star tower defense",
"all star tower defense x",
"alone: battle royale",
"alternate battlegrounds",
"alternate battlegrounds ",
"american plains mudding",
"amongst us!",
"an infinite road trip",
"animal sim: underwater",
"animal simulator",
"animal topia rp",
"animatronic world",
"anime adventures",
"anime battle arena",
"anime card clash",
"anime crusaders",
"anime dimensions",
"anime eternal",
"anime evolution",
"anime fighters simulator",
"anime fighting simulator",
"anime fruits",
"anime guardians",
"anime last stand",
"anime life",
"anime paint by numbers",
"anime raid",
"anime rangers x",
"anime spirits",
"anime vanguards",
"aniphobia",
"anomic",
"answer or die",
"apeirophobia",
"apocalypse rising",
"apocalypse rising 2",
"arcade basketball",
"arcade empire",
"arcane lineage",
"arcane odyssey",
"arcane reborn",
"archived",
"are you lonely?",
"are you okay?",
"are you smart?",
"arise crossover",
"arm battles",
"arm wrestle simulator",
"armless detective",
"armored patrol",
"army control simulator",
"army roads",
"arrest brainrot",
"arsenal",
"asura",
"asylum life",
"attack on albert",
"attack on titan revolution",
"attack on titan: last breath",
"attrition",
"avatar simulator",
"avengers tycoon",
"azure latch",
"azure mines",
"bLockerman's Minesweeper",
"backpacking",
"backrooms morphs",
"bad business",
"bad cat",
"baddies",
"badvaar v4",
"bakers valley",
"bakiez bakery",
"baldi's basics 3d morph rp",
"ball and axe",
"ballista",
"banana eats",
"bang marcave",
"barbie dreamhouse tycoon",
"barren",
"barry's prison run! (obby)",
"base battles",
"base wars",
"basically fnf",
"basically fnf: remix",
"basketball legends",
"basketball: zero",
"bathe da baby",
"bathroom attack",
"bathwick town",
"battle of the bulge roleplay",
"battleship battle",
"bayside high school",
"be a beggar!",
"be a hole",
"be a nurse",
"be a parkour ninja",
"be crushed by a speeding wall",
"be dead forever simulator",
"be fish",
"be npc or die!",
"beach simulator",
"bear (alpha)",
"beat bounce (geometry dash)",
"beat up dummies simulator",
"beat up simulator",
"become fumo",
"bedfight",
"bedwars",
"bee swarm simulator",
"beeface!",
"beeface: be a bee!",
"before the dawn: redux",
"before truth",
"ben 10 super hero time",
"bendy and the ink machine",
"berkeley county",
"berry avenue rp",
"better avatar?",
"better food?",
"beyblade x-battles",
"beyblade: rebirth",
"beyond",
"bid battles",
"big brain simulator",
"big city tycoon",
"big paintball 2!",
"big paintball!",
"bike of hell",
"bitcoin miner",
"black hole core",
"black hole survival!",
"black magic",
"blackhawk rescue mission 2",
"blackhawk rescue mission 5",
"blacksite zeta",
"blade ball",
"blade quest",
"blair",
"blast hook",
"blast zone",
"bleeding blades",
"block tales",
"block tycoon",
"blockate",
"blockerman's minesweeper",
"blocks n' props",
"blockspin",
"blood & iron",
"bloodfest",
"bloodlines",
"bloodtide",
"bloody battle",
"blox cards",
"blox fruits",
"blox fruits for roblox mods",
"blox hunt",
"blox loot",
"bloxverse: unlimited",
"bloxy bingo",
"blue lock: rivals",
"bobsled simulator",
"boku no roblox",
"bomber squadron",
"booga booga",
"book of monsters",
"boost vector",
"bordr gam",
"bots & muskets",
"boxing beta!",
"boxing league",
"boxing simulator",
"boxywood rp",
"brainrot +1 power",
"brainrot battlegrounds",
"brainrot classic evolution",
"brainrot evolution",
"brainrot jenga tower!",
"brainrot jumping",
"brainrot tower",
"brainrot tower defense",
"brainrot training",
"brainrot vs mecha",
"brainrot zombie evolution",
"break in",
"break in (story)",
"break in 2",
"break in 2 (story)",
"break in simulator",
"break your bones",
"breaking point",
"brick simulator",
"bridge battles!",
"british railway",
"broken bones iv",
"broken bones iv - ragdoll sim",
"broken hill nuclear power station",
"brookhaven",
"brookhaven rp",
"bubble gum simulator",
"bubble gum simulator infinity",
"bubu thieves",
"buckshot",
"build & survive",
"build a beehive【blood moon】",
"build a boat for treasure",
"build a brainrot factory",
"build a bunker!",
"build a car",
"build a cart",
"build a haven",
"build a hideout and sword fight",
"build a plane",
"build a roller coaster",
"build a tractor",
"build a zoo",
"build an island!",
"build and survive",
"build defense",
"build to survive",
"build to survive monsters!",
"build to survive!",
"build ur army",
"build ur army ⚔️",
"build ur base",
"build with blocks",
"build with friends",
"build, fight, steal! (beta)",
"bunny tale",
"burger game",
"burger game 🍔",
"bus stop simulator",
"busy business",
"button simulator: excavation discoveries",
"cabin crew simulator",
"cage fishing",
"camo troll tower",
"camping",
"camping 2",
"camping 3",
"canterbury & district bus simulator",
"capybara evolution",
"car battles",
"car crash",
"car crash simulator",
"car crash simulator 2",
"car crushers 1",
"car crushers 2",
"car crushers 2 - physics simulation",
"car dealership tycoon",
"car driving indonesia",
"car parking level 7",
"car suspension test",
"car tycoon! demo",
"carros rebaixados br (pre-alpha)",
"carry an egg",
"carry puzzles (teamwork obby)",
"cart ride",
"cart ride around nothing",
"cart ride into rdite!",
"case clicker",
"castle",
"cat simulator",
"cat vs mouse",
"cat's life",
"catalog avatar creator",
"catalog heaven",
"catch and feed a brainrot!",
"catwalk show",
"cbr3",
"centaura",
"chained",
"chained together",
"champion simulator",
"champions: summon your team",
"chaos jenga",
"chaos-canyon",
"cheese escape",
"cheese escape [horror]",
"cheese td",
"chicago: 1949",
"chicken jockey",
"christmas tycoon: save the christmas!",
"circle grinding incremental",
"circus trip",
"city architect",
"city life",
"city-17",
"clashers royale",
"classic sonic simulator",
"classic strike deluxe",
"classic: crossroads",
"claw machine arcade!",
"clicky keyboard tower",
"climb 1,",
"climb 1,000 stairs",
"climb 1000 stairs",
"climb and jump tower",
"climb and slide!",
"clip it",
"clone engine",
"clone kingdom tycoon",
"clone tycoon 2",
"clover online",
"club raven",
"club roblox",
"club roblox rp",
"codename: redux",
"collect all pets!",
"collect the body",
"color art: coloring games",
"color block",
"color escape!",
"color game!",
"color or die",
"combat arena",
"combat initiation",
"combat warriors",
"conquer the world",
"conquer the world ww2",
"container rng",
"control europe",
"conveyor sushi restaurant",
"convince the crazy maid to let you free",
"cook burgers",
"cook pizzas",
"cooking simulator",
"copyrighted artists",
"counter blox",
"country collectors",
"countryball world",
"county jail roleplay",
"cozy small park",
"crazy chefs!",
"crazy stairs",
"create a cart ride!",
"creature chaos",
"creatures of sonaria",
"creatures of sonaria survive kaiju animals",
"creatures tycoon",
"creeper chaos",
"criminal tycoon",
"criminal vs. swat",
"criminality",
"critical legends",
"critical strike",
"critical tower defense",
"crown academy",
"croydon: london bus simulator",
"croydon: the london transport game",
"cruise",
"cruise ship tycoon",
"cruiser wars!",
"crush for brainrots",
"cube combination",
"cube defense",
"cultivation: mortal to immortal",
"cursed islands",
"cursed tank simulator",
"custom pc tycoon!",
"cut trees",
"d-day",
"da block",
"da hood",
"dance your blox off",
"dandy's world",
"dangerous atv driving",
"dangerous horse riding",
"dangerous night",
"dashing simulator",
"databrawl",
"databrawl roleplay",
"dawn of aurora",
"daybreak",
"daycare",
"daycare 2",
"dead ahead",
"dead rails",
"dead sewers",
"deadline(roblox)",
"deadly heist",
"deadzone classic",
"dealership tycoon",
"death ball",
"death penalty",
"death zone",
"deathrun",
"decaying winter",
"dedoxed",
"deep descent",
"deep space tycoon",
"deep woken",
"deepwoken: duskguard",
"deermont",
"defend the statue: nostalgic proctors edition",
"defend the train beta",
"defender's depot",
"delta ring",
"delta worlds rpg",
"demon fall",
"demon slayer rpg 2",
"demon soul simulator",
"demon warriors",
"demonfall",
"demonology",
"desert bus(roblox)",
"design it!",
"destroy grandma",
"destruction simulator",
"die of death",
"diesel n' steel",
"dig the backyard",
"dig to china!",
"dig to earth's core!",
"dig to save brainrot",
"dimensional coalescence",
"dingus",
"dino bro tower",
"dino hunter",
"dinosaur simulator",
"dinosaur world mobile",
"disaster dome",
"disaster hotel",
"disaster island",
"disaster island survival",
"disaster master",
"dodgeball!",
"dog simulator",
"dog walk",
"dogecoin mining tycoon",
"don't get crushed by a giant rock",
"don't get eliminated",
"don't leave the circle!",
"don't press the button",
"don't press the button 4",
"don't wake the brainrots!",
"don't wake the fish!",
"donate game",
"doodle obby",
"doodle world",
"doomed",
"doomspire brickbattle",
"doors",
"doors but bad",
"double down",
"dow - dogs of war: ww2",
"dragon adventures",
"dragon ball n",
"dragon ball rage",
"dragon ball x",
"dragon ball z final stand",
"dragon blox",
"dragon soul | anime mmo",
"dragons' life",
"draw & switch",
"draw me!",
"draw or oof!",
"dream game",
"dreamville rp",
"dress to impress",
"drift paradise",
"drilling simulator",
"drive cars down a hill!",
"drive world",
"drive world drifting & racing",
"drivex",
"driving empire",
"driving empire car racing",
"driving simulator",
"dronepoint",
"dubai rp",
"dudes battlegrounds",
"duel warriors",
"dummies vs noobs",
"dummy counter your friends",
"dump",
"dungeon escape",
"dungeon heroes",
"dungeon master",
"dungeon quest",
"dungeon quest! rpg adventure",
"dungeon rng",
"dunking simulator",
"dusk",
"dust: wasteland survival",
"dynamic ship simulator i",
"dynamic ship simulator ii",
"dynamic ship simulator iii",
"dynasty: battlegrounds",
"easiest game on roblox!",
"easy glass bridge (possible squid game)",
"easy obby",
"easy size obby",
"eat a huge waffle",
"eat blobs simulator",
"eat or die",
"eat the world",
"eclipsis",
"eden orphan home",
"edward the man-eating train",
"effortless tower",
"eg!",
"egg farm simulator",
"egg hunt 2012",
"egg hunt 2013",
"egg hunt 2014",
"egg hunt 2015",
"egg hunt 2016",
"egg hunt 2017",
"egg hunt 2018",
"egg hunt 2019",
"egg hunt 2022",
"egg kevin's house",
"el gato tower",
"election simulator",
"electric state darkrp",
"elemental battlegrounds",
"elemental dungeons",
"elemental powers tycoon",
"elevator of fun",
"elevators",
"elimination",
"elimination tower",
"emergency emden",
"emergency hamburg",
"emergency response: liberty county",
"emergency world wide",
"empire roleplay",
"encounters",
"endangered world",
"endless horde",
"energy assault",
"entrenched",
"entrenched ww1",
"entry point",
"epic minigames",
"epic mining 2",
"escape angry head",
"escape evil grandpa! (obby)",
"escape papa pizza's pizzeria! (scary obby)",
"escape room",
"escape running head",
"escape the carnival of terror obby!",
"escape the lava",
"escape the tsunami",
"eternal towers of hell",
"evade",
"everything upgrade tree",
"eviction notice",
"evolution evade",
"examination",
"expedition antarctica",
"experience gravity",
"extraordinary adventures",
"factory rng",
"factory town tycoon",
"factory! car dealership tycoon",
"fall of hell",
"fallen survival",
"fame simulator",
"fantastic frontier",
"farming and friends",
"farmstead",
"fashion famous",
"fast food simulator",
"fe2 community maps",
"fear elevator",
"feather family",
"feed your pet!",
"fentanest",
"field of battle",
"field trip",
"field trip z",
"fight in a school",
"fight the monsters!",
"final stand 2",
"find the bfb characters!",
"find the brainrot",
"find the chomiks",
"find the floppa",
"find the markers",
"find the markers (320)",
"find the noobs 2",
"find the trollfaces!",
"fire fighting simulator",
"firefighters!",
"fireteam",
"firework simulator",
"fisch",
"fish game",
"fish go",
"fish it!",
"fishing simulator",
"five nights td",
"five nights td 2",
"five nights: hunted",
"fix it up!",
"flag wars",
"flag wars!",
"flashpoint",
"flee the facility",
"flicker",
"flight simulator",
"flightline",
"fling a friend!",
"fling things and people",
"flood escape",
"flood escape 2",
"flood rise",
"flood survival waves",
"fly a jetpack",
"fnaf: co-op",
"football fusion 2",
"forget your friend's birthday!",
"forgotten worlds",
"formula apex racing",
"forsaken",
"fortline",
"fpe:s",
"framed!",
"freddy fazblox's pizza roleplay",
"freddy's tycoon remastered",
"free admin",
"free draw",
"free items game!",
"free ugc obby (afk or play)",
"freeze tag",
"frenzy",
"frontlines",
"fruit battlegrounds",
"fruit forager",
"funk tower x",
"funky friday",
"gacha online",
"gacha online rp",
"galaxy",
"galleons",
"gang up on people simulator",
"garden tower defense",
"gardeners trading plaza",
"gas station simulator",
"gavin's story",
"gear slap tower",
"gef",
"generic cooking game",
"generic roleplay gaem.",
"geometry defense!",
"german voice",
"get a snack at 4 am",
"get a snack at 4 am: snackcore",
"get eaten!",
"ghost at the door",
"ghost simulator",
"ghost: samurai fighting",
"giant simulator",
"giant survival!",
"giga mansion tycoon",
"gladiators!",
"glide tower",
"glue piece",
"go fishing",
"goal kick simulator",
"gods of glory",
"gods will",
"goofy runners",
"gorilla tag ultra",
"grace",
"grace(roblox)",
"grand piece online",
"granny",
"granny(roblox)",
"grass cutting incremental",
"grass incremental",
"grave/digger",
"gravity shift",
"great school breakout! (first person obby)",
"greenville",
"ground crew simulator",
"ground war",
"grow a garden",
"growing up",
"grumpy gran! (scary obby)",
"guess italian brainrot or die",
"guesty",
"guide the bacons",
"gun armory tycoon",
"gun grounds ffa",
"gun simulator",
"gun testing",
"gunfight arena",
"gunung mono",
"gunung pedaunan",
"gunung yntkts",
"guts & blackpowder",
"gym league",
"gym showdown simulator",
"gym star simulator",
"hade's rng",
"halloween & limiteds | realistic car driving™",
"halloween obby!",
"hammer simulator",
"hamood habibi tower",
"happy land rp",
"happy oofday!",
"harbor east",
"harbor havoc",
"harmonytown rp",
"hcbb 9v9",
"hedgerows ii",
"heists",
"helicopters!",
"hell or heaven",
"hellmet",
"hello neighbor",
"henry stickmin 3d rp",
"hero brawl",
"heroes battlegrounds",
"heroes of robloxia",
"heroes online",
"hex",
"hexa game",
"hexaria",
"hide and seek extreme",
"hide and seek transform",
"hide n seek ultimate",
"hide or die!",
"hide the body",
"high school",
"highland park rp",
"hitman card game",
"hmm...",
"hole in the wall",
"holocene mobile",
"hood wars",
"horrific housing",
"horse life",
"horse race",
"horse rng",
"horse valley",
"horse world",
"hostile skies",
"hotel",
"hours",
"house tycoon",
"house tycoon 2",
"how to train your dragon",
"hungry pig",
"hunted",
"hunting season",
"hunty zombie",
"hutan",
"hypershot",
"hyundai mobility adventure",
"i don't feel so good simulator",
"i wanna run away tower",
"i wanna test the game (beta test)",
"ice cream simulator",
"icebreaker!",
"identity fraud",
"imposters & roles | among us",
"impostor",
"impostor | among us",
"in area 51",
"in plain sight",
"incognito",
"indo hangout",
"indo voice",
"industrialist",
"infamy",
"infection gunfight",
"infection inc.",
"infectious smile",
"infinite tower tycoon",
"infinity rpg",
"ink game",
"innovation arctic base",
"innovation inc. spaceship",
"innovation inc. thermal power plant",
"innovation labs",
"insane elevator!",
"insane troll slap tower",
"insomnia",
"interliminality",
"interminable rooms",
"interminable rooms[e]",
"international airport",
"invincible showdown",
"invisible hide and seek",
"invision's web-verse",
"ion formula racing",
"iq 0 jump rope glass bridge",
"iq test",
"iron assault",
"iron curtain",
"iron glory",
"iron man simulator",
"iron man simulator 2",
"island 2",
"island royale",
"islands",
"isle",
"isles of ravos",
"isolation",
"it girl",
"it lurks",
"it's mine",
"italian brainrot jump clicker",
"italian brainrot quiz",
"italian brainrot speed clicker",
"italian brainrot thieves",
"item asylum",
"itty bitty airport",
"itty bitty city",
"itty bitty railway",
"jailbreak",
"jet wars: advanced battle",
"jim's computer",
"jojo blox",
"jojo: crusaders' heaven",
"jojo:timestop battlegrounds",
"joodpakjai",
"jujutsu beatdown",
"jujutsu infinite",
"jujutsu shenanigans",
"jule's rng",
"jump clicker",
"jump showdown",
"jurassic blocky",
"just build!",
"just daytona. (2012 SOFT BODY)",
"just daytona. (2012 soft body)",
"k-pop demon hunter evolution",
"kaiju paradise",
"kaiju universe",
"kat - knife ability test",
"kayak racing",
"keyon air: flight simulator",
"keys",
"keys season 24",
"kick a brainrot",
"kick the baby",
"kill or be killed",
"killer stairs",
"king legacy",
"kitchen gun",
"kite combat",
"kitten game",
"kitty",
"kitty chapters",
"kj arena",
"knife capsules",
"knife simulator",
"kohls admin house bc",
"kohls admin house epix edition",
"kohls admin house nbc",
"koya dance studio",
"kpop demon hunters rp",
"kpop demon hunters speed clicker",
"lab experiment",
"lag test 2020",
"lasso animals",
"last run",
"last strandeds",
"last strandeds [standalone]",
"late to school",
"legends battlegrounds",
"legends of speed",
"legends re:written",
"let him go",
"lethal ape (forest update)",
"lewislife rp",
"lexington & concord",
"life in paradise",
"life of an otaku",
"life sentence",
"lifetogether rp",
"lifting simulator",
"light game",
"like or dislike",
"link to shovelware's brain game",
"little world",
"live in a back alley simulator",
"livetopia",
"livetopia rp",
"locofficial",
"locofficial!",
"lollipop simulator",
"lollipop tycoon",
"lolwut",
"longest obby in roblox",
"loomian legacy",
"lootify",
"lost",
"lost rooms",
"lucky avatars!",
"lucky block tower",
"lucky blocks battlegrounds",
"lumber tycoon 2",
"m.e.g. endless reality",
"mad city",
"mad dreams survival",
"mad games",
"mad paintball 2",
"magic simulator",
"magnet simulator",
"make a army!",
"makeup store simulator",
"making memes in your basement at 3 am tycoon",
"mall tycoon",
"manage your own country",
"manage yout own country 2",
"mansion",
"mansion tycoon",
"maple county",
"maple hospital",
"marble mania",
"marvel and dc super heroes",
"marvel omega",
"math murder",
"math tower race",
"meepcity",
"meet people across the world",
"mega fun obby",
"mega hide and seek!",
"mega mansion tycoon",
"mega miners",
"mega princess tycoon",
"megamech",
"meme sea",
"memories",
"merge tower defense - upd 6.0",
"mermaid testing",
"metro life city rp",
"mic up",
"michael's zombies",
"microwave dinner",
"midnight chasers: highway racing",
"midnight horrors",
"midnight racing: tokyo",
"mighty omega",
"military madness",
"military simulator",
"military tycoon",
"military tycoon ®",
"millionare empire tycoon",
"mine racer",
"miner's haven",
"mingle carousel",
"mingle practice (vampire part 1)",
"mini cities",
"mini cities 2",
"mini city tycoon",
"mining inc: remastered",
"mining simulator",
"mining simulator 2",
"miraculous™ rp: ladybug & cat noir",
"mm2 aim trainer",
"mmc zombies project",
"monday morning misery",
"monke game",
"monkey raft",
"monster madness survival",
"monsters of etheria",
"moon city",
"moon tycoon",
"morph world!",
"mortem metallum",
"mount atin",
"mount daun",
"mount rng",
"mount sibuatan",
"mount sumbing",
"mr.mix",
"mt. everest climbing roleplay",
"mugen",
"multicrew tank combat",
"murder",
"murder island 2",
"murder mystery 2",
"murder party",
"murderers vs sheriffs",
"murderers vs sheriffs 2",
"murderers vs sheriffs duels",
"murderers vs. sheriffs",
"muscle legends",
"musical chairs",
"mx world",
"my brainrot egg farm",
"my hello kitty cafe",
"my island!",
"my movie",
"my prison",
"my racing track",
"my restaurant!",
"my singing brainrot",
"my supermarket",
"my tycoon!",
"mystic battleground",
"n the jojo game",
"napoleonic wars",
"nations roleplay 2",
"natural disaster survival",
"nautica",
"naval 1918",
"naval warfare",
"navy simulator",
"need more heat",
"neighborhood war",
"neighbors",
"neo warfare x",
"neohee hot spring",
"neon district",
"new! anime life",
"newsmith rp",
"next door",
"nfl universe football",
"nft battle",
"nico's nextbots",
"night shift at paulie's (early beta)",
"ninja assassin",
"ninja challenge",
"ninja legends",
"ninja legends 2",
"ninja wizard simulator",
"nitro car",
"no man's wasteland",
"noob army tycoon",
"noob army tycoon 1",
"noob infection",
"noob train",
"noob wars!",
"noobs in combat",
"noobs vs zombies: realish",
"northwind",
"notoriety",
"notoriety: a payday® experience",
"nova hotels",
"npc or die!",
"nuclear blast testing facility",
"nuclear plant tycoon",
"nugget",
"oMega Obby 🌟 725 Stages!",
"oaklands",
"obby but you have long arms",
"obby but you're cursed",
"obby but you’re on a bike",
"obby creator",
"obby king remastered",
"obby squads",
"ocean man",
"octopus game",
"off-roading epic",
"office simulator",
"ohio.",
"omega obby 725 stages!",
"omnidroids test",
"one block",
"one fruit",
"one piece millennium",
"one piece new world",
"one piece open seas",
"one punch man unleashed",
"oobja",
"operation overlord",
"operation scorpion",
"operators",
"ophelia",
"opposer vr",
"ore tycoon 2",
"orthoxia",
"outbreak",
"outcome memories v0.1",
"outlaster",
"overblox",
"overlook bay",
"overnight",
"pacifico",
"pacifico 2: playground town",
"paint 'n guess",
"panik",
"panik 2",
"papers, please: border simulator",
"paracam",
"paradise rp",
"paranormica",
"parasite",
"parasite.exe",
"parkour",
"parkour obby",
"pass or die",
"pears to pairs",
"pembroke pines fl",
"penguin simulator",
"penthouse tycoon",
"peroxide",
"person299's minigames",
"pet fighting square!",
"pet heroes",
"pet legacy",
"pet party rp",
"pet ranch simulator 2",
"pet simulator",
"pet simulator 99!",
"pet simulator x!",
"pet story",
"petapeta",
"petapeta: school of nightmares",
"pets go!",
"phantom forces",
"phighting!",
"phobias",
"photoshoot x green screen studio",
"pick a side",
"pig 64",
"piggy",
"piggy: intercity",
"pilchero outfits",
"pilfering pirates",
"pillar chase 2",
"pilot training flight simulator",
"pinewood computer core",
"pinewood space shuttle advantage",
"pirate wars!",
"pistol 1v1",
"pixel blade",
"pizza factory",
"plane crazy",
"plane training",
"plants vs brainrots",
"plants vs zombies battlegrounds",
"plates of fate: remastered",
"play or die",
"pls donate",
"pocket pirates",
"podcasts",
"podiums vc",
"poison drinks",
"pokemon brick bronze",
"policesim:nyc",
"polish car driving",
"polybattle",
"pop it trading",
"portal heroes",
"possessor",
"power simulator",
"pressure",
"primal pursuit",
"prior extinction",
"prior extinction - retro",
"prison life",
"prison pump",
"prison royale",
"prison showdown",
"prisoner life",
"project : kaiju",
"project : rusher",
"project baki 2",
"project delta",
"project egoist",
"project flight",
"project jojo",
"project lazarus: zombie",
"project menacing",
"project pokemon",
"project slayers",
"project smash",
"project star",
"project stardust",
"project xl",
"project: escape room",
"project: lazer",
"project: opm",
"project: scp",
"prospecting!",
"protect the house from monsters",
"pubg | ببجي العرب",
"public bathroom simulator",
"pull a sword",
"pummu talladega (2024 gen 7 soft body)",
"punch monsters!",
"punch wall",
"purple skittles",
"q-clash!",
"qs energy research facility",
"quarantine-z",
"quiet or die!",
"race around the world",
"race clicker",
"racer vs police ai",
"racket rivals",
"radiant residents",
"raft tycoon",
"ragdoll engine",
"ragdoll system test",
"ragdoll universe",
"rail frenzy",
"rails unlimited",
"rainbow friends",
"raise a bloppa",
"raise a floppa",
"raise a floppa 2",
"raise animals",
"ramen simulator",
"random tool (4.68)",
"randomizer: redux",
"rate my avatar",
"ray's mod",
"rblxware",
"rcl battlegrounds",
"re:infected",
"ready 2 die",
"realistic guns (fps shooter)",
"realistic hand rp without vr",
"realistic hood testing",
"realistic street soccer",
"reaper 2",
"reaper simulator",
"reason 2 die",
"reason 2 die: awakening",
"rebirth champions: ultimate",
"rec it",
"recoil",
"red ball 4!",
"red light, green light",
"red vs blue plane wars!",
"redcliff city rp",
"redwood prison",
"refinery caves",
"regretevator",
"regretevator [elevator simulator]",
"rensselaer county",
"repair a car",
"resort tycoon 2",
"restaurant tycoon",
"restaurant tycoon 2",
"restaurant tycoon 3",
"retail tycoon",
"retail tycoon 2",
"retro tds",
"retroblox",
"retrostudio",
"revenge of the slimes!!!",
"rex: reincarnated",
"rh dance studio",
"rhythm track",
"ride a cart down a slide",
"ride a rocket to the space station and moon!",
"ride and slide!",
"rift royale",
"right 2 fight",
"rip brainrot",
"ripull minigames",
"rise of nations",
"risk universalis",
"rivals",
"ro-bio",
"ro-boxing",
"ro-chanics",
"ro-ghoul",
"ro-piece",
"roach",
"rob the house",
"robeats",
"roblox - containment breach",
"roblox - realistic forest demo",
"roblox high school",
"roblox high school 2",
"roblox is unbreakable",
"roblox point - theme park",
"roblox rally racing",
"roblox titanic",
"roblox uno",
"roblox wwii",
"roblox_egor game",
"robloxian highschool",
"robloxian waterpark",
"robot 64",
"robowling",
"rocitizen",
"rocitizens",
"rockefeller street",
"rocket simulator",
"rocket tester",
"rogue demon",
"rogue lineage",
"rokadia",
"roller skate obby",
"rolling thunder",
"rolling thunder pve",
"ronald",
"rooms",
"rooms & doors",
"rooms:low detailed○",
"rooms:low detailed○[e]",
"rope battles",
"rope swing obby",
"rosebridge",
"roville",
"royale high",
"royalehigh",
"rpg elevator● file:south korea...",
"rpg simulator",
"rpg world",
"run hide fight",
"runners' path",
"running from the internet",
"rush point",
"s.c.p. site-19 roleplay",
"saber showdown",
"saber simulator",
"sacrifice sanctuary",
"sail and sink simulator!",
"sakura stand",
"salon de fiestas",
"salon makeover",
"samsung space tycoon",
"sandbox",
"sans multiversal battles! 2",
"sapien",
"savannah life",
"scary sushi",
"science simulator!",
"scp anomaly breach 2",
"scp games and scp monsters",
"scp rbreach",
"scp tower defense",
"scp tycoon",
"scp: area - 02",
"scp: daybreak",
"scp: devolved",
"scp: facility lockdown",
"scp: roleplay",
"scp: site roleplay",
"scp: the red lake",
"scribble showdown",
"scuba diving at quill lake",
"scuba diving at quill lake 🤿",
"sea cleaning simulator",
"seaside rp city rp",
"secret killer",
"secret staycation",
"sfs flight simulator",
"shadovis rpg",
"shadow run",
"shark evolution",
"sharkbite 2",
"sharkbite 2•",
"sharkbite•",
"sharp",
"shell shock",
"shellshock",
"shindo life",
"shinobi life",
"shipping lanes",
"shoot a brainrot!",
"shoot out!",
"short creepy horror stories",
"short horror games",
"shouting simulator",
"shouting simulator 2",
"shred",
"shred a brainrot",
"shrek in the backrooms",
"shrek in the backrooms link",
"shrink hide & seek",
"silence",
"silent assassin",
"silent mansion",
"silly simon says",
"simply smashing",
"sing it! karaoke battles",
"sinking ship",
"sinking ship simulator",
"site - 17",
"site-35",
"site-61",
"skateboard obby",
"skateboard of hell obby",
"ski resort",
"skibi defense",
"skibidi toilet battle boom",
"skibidi tower defense",
"skyblock tycoon 2",
"skywars",
"slap battles",
"slap tower",
"slap tower 4",
"slap tower 99",
"slayer battlegrounds",
"slayer tycoon",
"slayers unleashed",
"slendytubbies vs redux",
"slimeulator",
"snake simulator",
"snipe or die",
"sno day",
"snow shoveling simulator",
"snowball fighting simulator",
"snowballer",
"snowboard obby world 8",
"snowman simulator",
"social experiment",
"sol's rng",
"sol's rng● file:south korea...",
"something evil will happen",
"sonic speed simulator",
"sonic.exe: the disaster",
"sorcerer battlegrounds",
"sorcerer fighting simulator",
"soulshatters test place",
"sound volblox",
"south bronx: the trenches",
"southwest florida beta",
"space frontier",
"space jam",
"space mining tycoon",
"space sailors",
"space tycoon",
"special forces simulator",
"specter",
"specter: legacy",
"speed clicker",
"speed draw!",
"speed race",
"speed run 4",
"speed simulator",
"spider",
"spider simulator",
"spindown",
"splash",
"sponge",
"spongebob tower defense",
"spray paint!",
"sprunki plus",
"squid game",
"squid game tower",
"squid game x",
"squid game: the final games",
"st : blockade battlefront",
"stand upright",
"stand upright: rebooted",
"stands awakening",
"star wars oa",
"star wars: battlefield",
"star wars: heroes vs villains link",
"star wars: space battle",
"starscape",
"starving artists",
"state of anarchy",
"stateview prison",
"steal a brainrot",
"steal a clown",
"steal a drawn brainrot",
"steal a fish!",
"steal a glitch",
"steal a phone",
"steal a slap!",
"steal brainrots trading plaza",
"steal cookies",
"stealth",
"steep steps",
"stepford county railway",
"steve's one piece",
"stick battles",
"stop it, slender!",
"store empire",
"storm chasers 2",
"streamlined",
"street life remastered",
"street racing unleashed: the reborn beta 1.3.0",
"strife!",
"strongest punch simulator",
"strongman simulator",
"submarine simulator",
"subway simulator",
"subway testing remastered",
"sunset city",
"sunset plain",
"sunshine islands bus simulator",
"super blocky ball",
"super bomb survival",
"super cube cavern",
"super doomspire",
"super golf!",
"super hero tycoon",
"super league soccer",
"super league soccer!",
"super paper roblox",
"super power fighting simulator",
"super power training simulator",
"super roblox fighter",
"super speed run",
"super speed tycoon: playground",
"supermarket simulator",
"supermarket together",
"survival zombie tycoon",
"survive and kill the killers in area 51",
"survive and kill the killers in area 51 !!!",
"survive in area 51",
"survive on a raft",
"survive overnight in a bunker",
"survive overnight in a mega store",
"survive overnight in a school",
"survive the disasters",
"survive the disasters 2",
"survive the end of roblox",
"survive the killer!",
"survive the lava!",
"survive the night",
"survive the red dress girl",
"survivor",
"sushi tycoon",
"sword fighters simulator",
"sword fights on the heights iv",
"swordburst 2",
"swordburst 3",
"swordburst-online",
"tactical assault",
"tank simulator",
"tank warfare",
"tankery",
"task force",
"taxi boss",
"taxi simulator 2",
"team fortress 2 vs",
"team school breakout! (teamwork obby)",
"team soccer (3 vs. 3)",
"teamwork obby",
"teamwork puzzles (obby)",
"teamwork puzzles 2 (obby)",
"teddy",
"temple thieves",
"terminal",
"terminal [escape room]",
"terminal railways",
"terraria rpg",
"texting simulator",
"the $1,",
"the apocalypse",
"the backrooms",
"the backrooms [ redacted ]",
"the backrooms with guns",
"the battle bricks",
"the butchery",
"the clown killings reborn",
"the concorde experience",
"the conquerors 3",
"the cool zone",
"the corner",
"the crazy disasters!",
"the crazy elevator",
"the crusher",
"the day the noobs took over roblox 2",
"the difficulty upgrade tree: regrown",
"the doom wall 2: burst",
"the dropper",
"the elevator - remade",
"the final stand 2",
"the floor is lava",
"the floor is lava!",
"the future",
"the highest ever waterslide obby",
"the horror elevator",
"the horror mansion",
"the ink workshop",
"the intruder",
"the island",
"the labyrinth",
"the logo quiz!",
"the long drive",
"the maze",
"the mimic",
"the mimic classic",
"the mirror",
"the noob experiment battlefront",
"the normal elevator",
"the north pole",
"the northern frontier",
"the plaza",
"the plaza 2",
"the powder box (all ages)",
"the presentation experience",
"the rake fan remake",
"the rake remastered",
"the robloxia: until dawn",
"the scary button",
"the scary elevator",
"the schoolhouse",
"the space simulator",
"the stalker: reborn#",
"the streets",
"the strongest battlegrounds",
"the survival game",
"the trials",
"the underground war",
"the vibe cafe",
"the waiting room",
"the wild west",
"theif simulator",
"theme park tycoon 2",
"therapy",
"therapy 🔊",
"this is no simulator!",
"those who remain",
"timber!",
"timebomb duels",
"tiny sailor's: world™",
"titanic legacy",
"tix factory tycoon",
"tix memorial",
"tnt rush",
"tod",
"together",
"toilet tower defense",
"toilet world roleplay 2",
"tokyo claw machine",
"tongue battles",
"top roblox runway model",
"tornado alley ultimate",
"tornado simulator 2",
"total roblox drama",
"touch football",
"touch hockey",
"touch soccer",
"touch tennis",
"touch volleyball",
"touhou tower assault",
"tower battles",
"tower battles: battlefront",
"tower blitz",
"tower creator",
"tower defenders",
"tower defense simulator",
"tower defense x",
"tower defense x: beta",
"tower heroes",
"tower of coffee (coffee tower)",
"tower of hell",
"tower of zombies",
"tower simulator",
"town",
"toy defense",
"toy soldierz",
"tps street soccer",
"trade a brainrot",
"tradelands",
"traffic rush",
"train dog to fight",
"train to fight",
"train vs car ultimate",
"trains",
"transformers: prime",
"transfur infection 2",
"transfurmation",
"transport simulator 2021",
"treasure hunt simulator",
"treelands",
"trench war",
"trench warfare",
"trenches",
"trenches : beta",
"trespasser",
"trollge universe incident",
"tropical resort tycoon",
"try to die",
"tsunami game",
"ttd 3",
"twenty one",
"twilight daycare!rp",
"twisted",
"twisted(roblox)",
"two piece",
"tycoon rng",
"type or die",
"type: //soul",
"type://soul",
"typical colors 2",
"ultimate battlegrounds",
"ultimate driving",
"ultimate mining tycoon - update!",
"ultimate tower defense simulator",
"ultra toilet roleplay 2",
"unbox a 99 nights in the forest",
"unboxing rng!",
"unboxing simulator",
"undead defense tycoon",
"undercover trouble",
"underground war 2.0",
"undersiders",
"undertale survive the monsters!",
"undertale test place reborn",
"undertale tower defense",
"undertale: judgement day",
"unit 1968",
"unit: classified",
"universal roblox theme park",
"untitled boxing game",
"untitled door game",
"untitled door game 2",
"untitled fling game",
"untitled forsaken engine",
"untitled parkour game",
"untitled tag game",
"untitled tag game [recode]",
"unwavering soul",
"vacation",
"valley prison",
"valley prison roleplay",
"vampire hunters 3",
"vehicle legends",
"vehicle legends cars!",
"vehicle simulator",
"vehicle tycoon",
"ventureland",
"verdant moon",
"verse piece",
"vesteria",
"vfs flight simulator",
"violence district",
"virus border roleplay",
"visionary dance studio",
"volcano escape 2",
"volleyball 4.2",
"volleyball legends",
"volt",
"voxel block builder",
"voxel destruction physics",
"voxel playground",
"voxel sandbox",
"voxels legacy",
"voxlblade",
"wacky wizards",
"waitomo glowworm caves",
"wall hop practice",
"wanted",
"war age tycoon",
"war machines",
"war of the worlds",
"war simulator",
"war tycoon",
"warfare",
"warfare tycoon",
"warlords",
"warm isolation",
"warrior cats: ultimate edition",
"warships!",
"water park world",
"watermelon go!",
"waterpark",
"wave evasion",
"weak legacy 2",
"weapon fighting simulator",
"weaponry",
"webbed!",
"weight lifting simulator",
"weird gun game",
"weird strict dad",
"weird strict dad [🎉ANNIVERSARY]",
"welcome to bloxburg",
"welcome to roblox building",
"welcome to town of robloxia",
"westbound",
"whatever floats your boat",
"when the",
"where's santa",
"where's the baby!",
"white house simulator",
"wild horse islands",
"wild revolvers",
"wings of glory",
"wisteria",
"witching hour",
"wizard simulator",
"wizard tycoon - 2 player",
"wizard west",
"word bomb",
"work at a burger place",
"work at a pizza place",
"work at an airport!",
"work together! gs25 file:south korea...",
"world // zero",
"world // zero anime rpg",
"world conquest",
"world defenders",
"world expedition",
"world of magic",
"world of stands",
"world.io",
"would you rather..?",
"write a letter",
"yahayuk mount v.02",
"yeet a friend!",
"yet another funkin' night",
"your bizarre adventure",
"your goblin mine!",
"youtube simulator",
"youtuber tycoon!",
"zach's service station",
"zaibatsu",
"zealous fighter",
"zeppelin wars",
"zo samurai sword fighting",
"zombie attack",
"zombie buisness",
"zombie game",
"zombie merge tycoon",
"zombie rampage",
"zombie rush",
"zombie stories",
"zombie strike",
"zombie tycoon",
"zombie uprising",
"zombies vs humans",
"zoo or oof",
"zoo tycoon",
"zooo",
"zoぞ",
"zulu wars",
"{UPD10}Shoot Train: Spider Attack",
"{upd10",
"}shoot train: spider attack",
"Армия Роблокса РП",
"армия роблокса рп",
"☄️Don't Press The Button 4",
"⚔️ skywars 🏹",
"⚡ BIG Paintball 2!",
"⚡Ninja Legends",
"⚡Race Clicker",
"⛏️ Dig to Earth's CORE!",
"⛏️Dig to Save Brainrot",
"✈RED VS BLUE PLANE WARS!",
"✈️ Build A Plane",
"✈️Cabin Crew Simulator",
"✨ Build a Car",
"✨Collect The Body",
"❓ LUCKY BLOCKS Battlegrounds",
"⭐DoW⭐ - Dogs of War: WW2",
"⭐NEW! Anime Life",
"【update】full self driving/autopilot simulator",
"【🧹UPDATE🎃】Full Self Driving/Autopilot Simulator",
"种植花园",
"🃏 borderland",
"🌊 Raft Tycoon",
"🌋 Climb and Slide! [LAVA WORLD]",
"🌎 World.io",
"🌳 Lumber Tycoon 2",
"🌺 Build A Beehive【Blood Moon】",
"🍕Work at a Pizza Place",
"🍬 [CANDY] 🚂 Ride and Slide!",
"🎃 99 Nights in the Jungle",
"🎃 Creatures of Sonaria 🦇 Survive Kaiju Animals",
"🎃 Da Block 💥",
"🎃 Dandy's World [ALPHA]",
"🎃 Dragon Soul | Anime MMO 🐲",
"🎃 FACTORY! Car Dealership Tycoon",
"🎃 Harbor Havoc",
"🎃 Hell Or Heaven",
"🎃 Horrific Housing",
"🎃 Horse Life 🐎",
"🎃 KOYA DANCE STUDIO",
"🎃 Mega Mansion Tycoon 🌴🛥️",
"🎃 Oaklands [HALLOWEEN]",
"🎃 Peroxide 🍬 [HOLLOWEEN]",
"🎃 Pet Simulator 99! 👻",
"🎃 Your Bizarre Adventure 🎃",
"🎃 [SALE] Bubble Gum Simulator INFINITY",
"🎃Dungeon Heroes ⚔️",
"🎃Halloween & Limiteds | Realistic Car Driving™",
"🎃Quiet or Die!",
"🎃[HALLOWEEN] BEAR (Alpha)",
"🎃⌛[OCT 23] Blair",
"🎃🍣 Conveyor Sushi Restaurant",
"🎃👻[NEW] Life Sentence",
"🎆Color Escape! [LIGHT FESTIVAL!]",
"🎠 Mingle Carousel [SQUID GAME 2]",
"🎤 My Singing Brainrot",
"🎥My Movie",
"🎨 Anime Paint by Numbers",
"🎨Draw Or Oof!",
"🎫Build a Zoo[Season 2]",
"🎭 Steal a Glitch",
"🏀Basketball Legends🏀",
"🏁 Parkour Obby [W7]",
"🏙️ Mini City Tycoon",
"🏜️ Block Tales [DEMO 4]",
"🏝️ My Island! [SPOOKY]",
"🏠 House Tycoon",
"🏡Deermont🏡 [RP]",
"🐔 Animal Simulator",
"👺Demon Warriors",
"👻 Murderers VS Sheriffs DUELS 👻",
"💀 Hide or Die!",
"💀 SharkBite 2 🦈",
"💥 Flag Wars!",
"💥SNIPE OR DIE [FPS]",
"💪Muscle Legends",
"💰 Deadly Heist 💰",
"📸PhotoShoot x Green Screen Studio",
"🔑Project: Escape Room [NEW MAP🐵]",
"🔥 Hypershot",
"🔥Survive the LAVA!",
"🔨 Build with Blocks",
"🔨 MM2 Aim Trainer",
"🔨 Voxel Block Builder [🔥UPD]",
"🔨Plane Crazy🔨 [UPDATE]",
"🔨Voxel Playground",
"🔪Survive the Killer!",
"🚀[Planet X] The Space Simulator",
"🚌 Sunshine Islands Bus Simulator [NEW]",
"🚍Diesel n' Steel",
"🚒 Firefighters!",
"🚔 Jailbreak [Update]",
"🚣‍♂️Kayak Racing [UPD] 🔥",
"🚩Expedition Antarctica",
"🛠️Build and Survive",
"🛴Super Speed Tycoon🛴: Playground",
"🥊Punch Monsters!🥊",
"🪑Shrek in The Backrooms"
]

ROBLOX_LISTS = [game.lower() for game in list(set(ROBLOX_LISTS))]