GAME_SYNONYMS_DICT = {
    "怪物猎人": ["怪猎"],
    "Honor of Kings": ["hok", "王者国际服", "王者海外版"],
    "王者荣耀": ["王者荣耀", "王者"],
    "Grand Theft Auto": ["GTA"],
    "Call of Duty: Black Ops 6": ["BO 6", "BO6", "BO VI"],
    "Call of Duty: Black Ops 4": ["BO 4", "BO4", "BO IV"],
    "Call of Duty: Black Ops 3": ["BO 3", "BO3", "BO III"],
    "Call of Duty: Black Ops 2": ["BO 2", "BO2", "BO II"],
    "Call of Duty: Black Ops": ["BO 1", "BO1", "BO I"],
    "Call of Duty: Modern Warfare": ["MW", "MW 1", "MW1", "MW I"],
    "Call of Duty: Modern Warfare III": ["MW3", "MW3 2023", "MW 3"],
    "Call of Duty: Modern Warfare II": ["MW 2", "MW 2022", "MW2", "MW II"],
    "Call of Duty: Vanguard": ["COD Vanguard", "COD V"],
    "Call of Duty: Black Ops Cold War": ["BO Cold War", "BO CW"],
    "Mscience": ["Msciense"],
    "明末：渊虚之羽": ["明末", "明末渊虚之羽", "明末渊虚", "明末渊虚之羽", "明末：渊虚之羽", "明末:渊虚之羽", "明末: 渊虚之羽"],
    "little nightmares": ["little nightmare"],
    "逃离鸭科夫（Escape from Duckov）": ["逃离鸭科夫", "逃离鸭可夫"],
    "NBA 2K25": ["NBA 2K 25", "NBA2K 25"],
    "SOC(Survival Open World Crafting)": ["SOC"],
    "Dying Light: The Beast": ["DLTB", "DL TB", "DL:TB", "DL：TB", "the beast", "dying light the beast", "dying light: the beast"],
    "Elden Ring Nightreign": ["elden ring nightreign"],
    "8 Ball Pool": ["八球", "8 ball pool", "8ballpool", "8ball", "8球", "8 球", "8BP", "8 bp"],
    "猎天使魔女": ["类天使魔女", "泪天使魔女", "贝优妮塔"],
    "Digital Extremes": ["DE", "DigEx", "DEX"],
    "10 Chambers Collective": ["10 Chambers", "10cc", "10 CC", "10 Chambers Collective", "10C", "10 C", "10CH", "10 CH"],
    "Sumo Digital Studio": ["Sumo Digital", "Sumo"],
    "Grinding Gear Games": ["GGG", "G-Games", "G Games", "GrindGear", "Grinding Gear"],
    "Electronic Arts": ["EA"],
    "Lab42": ["L42"],
    "Splash Damage": ["SPD"],
    "Scopely": ["SCP"],
    "Ironhide Games": ["Ironhide Games", "IHG"],
    "Lucid Games": ["LGames"],
    "headlock": ["HDLK"],
    "PixelAnt Games": ["PixelA"],
    "Fulqrum Publishing": ["FLQ Publishing", "FLQ"],
    "Miniclip": ["MClip", "MiniClip"],
    "Blizzard Entertainment": ["Blizzard", "Blizz", "Blizzard Entertainment", "Blizzard Game Studio", "Blizzard Game"],
    "SYBO Studio": ["SYBO", "SYBO Studio", "SBO", "SYBO Game"],
    "Riot Games": ["Riot"],
    "Roblox": ["RBLX"],
    "Secret Mode": ["SMode"],
    "Funcom": ["FunC", "FCOM"],
    "Platinum Games": ["PlatG"],
    "Forza Horizon 6": ["forza 6"],
    "Turtle Rock Studios": ["TRS"],
    "Zenless Zone Zero": ["ZZZ"],
    "Inflexion Games": ["INFX", "INF Games"],
    "Sharkmob Studio": ["SHM", "Sharkmob"],
    "Fatshark Studio": ["FShark", "F-Shark", "FatShark"],
    "VNG Corporation": ["VNG", "VNGC"],
    "Highguard": ["High guard", "HIGAR"],
    "Anno 117: Pax Romana": ["Anno Pax Roma 177", "Anno 117 Pax Romana"],
    "Stunlock Studios": ["Stunlock", "SLock"],
    "YAGER Development Studio": ["YAGER", "YAGER Studio", "YAGER Game Studio", "Yager", "YGR", "YAGER Development Studio", "YAGER Development"],
    "Phantom Games Studio": ["PG", "Phantom Games", "Phantom Games Studio", "PG Studio"],
    "Techland Game Studio": ["Techland", "TLD", "Techland Game Studio", "TLand"],
    "Hollow Knight: Silksong": ["Hollow Knight: Silksong", "丝之歌", "silksong", "hk丝之歌", "hk silksong", "silk song", "silksong", "Hollow Knight Silksong"],
    "Call of Duty Mobile": ["使命召唤手游", "使命召唤手游国际服", "使命召唤手游海外版", "codm", "cod mobile", "使命召唤移动端"],
    "猎天使魔女4": ["新一代的类天使魔女", "新一代的泪天使魔女", "新一代的贝优妮塔", "新一代的猎天使魔女", "新一代猎天使魔女"],
    "黑神话：悟空": ["黑神话悟空", "黑悟空", "黑猴", "黑悟空", "黑神话：悟空", "黑神话悟空"],
    "黑神话：钟馗": ["黑神话钟馗", "黑钟馗", "黑馗", "黑神话：钟馗", "黑神话钟馗"],
    "《彩虹六号》": ["彩六", "彩6", "彩 6"],
    "《生化危机 9》": ["生化9", "生化九"],
    "Steam Top Wishlists": ["Steam Top Wishlists", "Steam Top Wishlist","Top Wishlists", "Top Wishlist", "steam top wishlists", "steam top wishlist","top wishlists", "top wishlist", "wishlist排名"],
    "沙丘：觉醒": ["沙丘觉醒", "沙丘：觉醒", "沙丘"],
    "Dune: Awakening": ["Dune", "Dune: Awakening", "Dune Awakening"],
    "Path of Exile 2": ["poe2", "poe 2"],
    "上线后第一个月": ["首月", "上线首月"],
    "零售销量（Physical Units）": ["零售销量"],
    "零售收入（Physical Revenue）": ["零售收入"],
    "解限机": ["解线机", "解限鸡", "解线鸡", "姐先机"],
    "过去半年": ["前6个月", "过去6个月", "过去六个月", "前六个月"],
    "over the past half year": ["over the last 6 months", "over the past 6 months"],
}

# for each key of GAME_SYNONYMS_DICT, add the key to the synonyms list
for key in GAME_SYNONYMS_DICT:
    GAME_SYNONYMS_DICT[key].append(key)
    # 防止 Dying Light: The Beast 被替换成为 Dying Light: Dying Light: The Beast
