import { readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { Config } from "@docusaurus/types";
import type { Options as DocsOptions } from "@docusaurus/plugin-content-docs";
import { themes as prismThemes } from "prism-react-renderer";

import { DOC_SLUGS, DOC_ORDER } from "./src/lib/docOrder";
import { LANGUAGES } from "./src/lib/locale-constants";
import legacyHeadingIds from "./src/remark/legacy-heading-ids";
import marketSourceDevPlugin from "./src/plugins/market-source-dev";
import scopeSiteCssPlugin from "./src/plugins/scope-site-css";

/**
 * Flowy Agent Store 官网 —— Docusaurus 站点配置。
 *
 * 三类页面并存：产品落地页（`src/pages/`）、市场目录页（`/market`）、双语文档站
 * （`/zh-CN/docs/…` 与 `/en-US/docs/…`），另有一份 `src/theme/` 下的站点外壳。
 *
 * **刻意不启用 Docusaurus 的 i18n。** 文档源树 `content/docs/{zh-CN,en-US}/` 与上游
 * `Michael-Lfx/allo` 同步，正文里的站内链写死为 `/zh-CN/docs/x` 与 `/en-US/docs/x`
 * （每种语言 70 处）。Docusaurus 的 i18n 会**省掉默认语言前缀**（zh-CN 文档变成 `/docs/x`），
 * 与这些链接以及线上既有 URL 全部冲突。因此改用**两个 docs 插件实例**：各指向一个语言目录、
 * 各自保留带前缀的 `routeBasePath`，于是 URL 与迁移前逐个一致，`content/docs/` 一个字都不用改。
 *
 * 产物是纯静态文件：`bun run build` → `build/`，由 EdgeOne Makers 托管。
 */

const siteDir = path.dirname(fileURLToPath(import.meta.url));

/**
 * 构建期校验：侧边栏顺序表必须覆盖 `content/docs/` 里真实存在的每一页。
 *
 * `content/docs/` 来自上游同步、**不带 front matter**，所以「有哪些页」只能由磁盘决定，
 * 而「按什么顺序展示」写在 `src/lib/docOrder.ts`。两者一旦脱节，新文档会静默地从侧边栏消失
 * ——正是旧站 `prerender()` 清单漏页那类缺陷的等价物，所以这里宁可让构建失败。
 */
function assertDocOrderCoversAllPages(): void {
  const expected = new Set(DOC_SLUGS);
  for (const lang of LANGUAGES) {
    const dir = path.join(siteDir, "content", "docs", lang);
    const onDisk = new Set(
      readdirSync(dir)
        .filter((name) => name.endsWith(".md"))
        .map((name) => name.replace(/\.md$/, "")),
    );
    const missing = [...onDisk].filter((slug) => !expected.has(slug));
    const stale = [...expected].filter((slug) => !onDisk.has(slug));
    if (missing.length || stale.length) {
      throw new Error(
        `[docusaurus.config] src/lib/docOrder.ts 与 content/docs/${lang}/ 不一致：` +
          `${missing.length ? `未登记 ${missing.join(", ")}` : ""}` +
          `${missing.length && stale.length ? "；" : ""}` +
          `${stale.length ? `已登记但磁盘上不存在 ${stale.join(", ")}` : ""}`,
      );
    }
  }
}

assertDocOrderCoversAllPages();

/**
 * docs 插件实例。
 *
 * 本分支（`test/docs-default-theme`）**回归 theme-classic 原生文档页**：不再 swizzle
 * `@theme/DocItem`，侧边栏、页内目录、面包屑、上下页导航全部交给原生主题渲染，
 * 排版交给 Infima。
 */
function docsPlugin(lang: string): [string, DocsOptions] {
  return [
    "@docusaurus/plugin-content-docs",
    {
      id: lang,
      // 源树就是仓库里既有的双语目录，与上游同步脚本的约定保持不动。
      path: `content/docs/${lang}`,
      routeBasePath: `${lang}/docs`,
      /**
       * 刻意**不写** `sidebarPath`（即 `undefined`）：原生行为是自动生成侧边栏
       * （`docs: [{ type: 'autogenerated', dirName: '.' }]`），标题取自各文档的 h1。
       * 之前写 `sidebarPath: false` 是为了让站点自绘侧边栏，本分支不再需要。
       */
      // 面包屑用原生默认（true），恢复「文档 / 当前页」层级。
      /**
       * 用**旧站的 slug 算法**覆盖标题锚点 id。
       *
       * 文档正文里写死了指向旧 id 的站内锚点（如 configuration.md 的
       * `#mcp-json-声明-mcp-server`），而 Docusaurus 默认的 github-slugger 会得到
       * `mcpjson声明-mcp-server`——锚点会静默失效，`onBrokenAnchors: "throw"` 还会把构建打红。
       * 该插件必须排在 `beforeDefaultRemarkPlugins`：内置的 headings / toc 插件会读取它写入的 id。
       */
      beforeDefaultRemarkPlugins: [legacyHeadingIds],
    },
  ];
}

const config: Config = {
  title: "Flowy Agent Store",
  tagline: "本地优先的单文件 Agent 运行时",
  favicon: "favicon.ico",

  // 线上由 EdgeOne Makers 托管；子路径部署用 BASE_PATH 覆盖（与旧站一致）。
  url: "https://agent-store.flowyaipc.cn",
  baseUrl: process.env.BASE_PATH ?? "/",

  organizationName: "Michael-Lfx",
  projectName: "agent-store-site",

  onBrokenLinks: "throw",
  onBrokenAnchors: "throw",
  // 文档正文的站内链是绝对路径（`/zh-CN/docs/x`），由 docs 插件校验；
  // Markdown 里的相对 `.md` 链接（上游同步过来的文件用不到）在这里只警告。
  markdown: {
    // 纯 Markdown 解析：正文含 `<n>`、`{...}` 这类 CommonMark 文本，走 MDX 会被当成
    // JSX / 表达式解析并报错；站点不写 MDX，所以整站按 `md` 处理（GFM 表格与代码块不受影响）。
    format: "md",
    mermaid: false,
    hooks: { onBrokenMarkdownLinks: "warn" },
  },

  // 只声明一个 locale：站点用 URL 前缀区分语言，不借 Docusaurus 的 i18n 机制（见文件头说明）。
  i18n: { defaultLocale: "zh-CN", locales: ["zh-CN"] },

  /**
   * 纯 Markdown 解析。文档正文含 `<n>`、`{...}` 这类 CommonMark 文本，走 MDX 会被当成
   * JSX / 表达式解析并报错；站点不写 MDX，所以整站按 `md` 处理（GFM 表格与代码块不受影响）。
   */
  // （已并入上面的 `markdown` 配置块。）

  // 市场树（约 22.6k 文件）刻意不放 `static/`：构建期拷贝会拖垮构建，
  // 且线上只托管目录页头像（见 scripts/copy-market-tree.mjs）。
  staticDirectories: ["static"],

  presets: [
    [
      "classic",
      {
        // 文档由上面两个显式实例提供；博客与默认 docs 都不需要。
        docs: false,
        blog: false,
        pages: { path: "src/pages" },
        theme: {
          /**
           * **本分支的关键改动**：全局只加载 `docusaurus-overrides.css` + 站点设计系统。
           *
           * 注意一个硬约束：**Docusaurus 把所有 CSS 合并进单个 `styles.css`**
           * （`@docusaurus/core/lib/webpack/base.js` 的 `cacheGroups.styles` 带 `enforce: true`，
           * 官方注释写明是为了避免多 CSS chunk 的加载顺序不确定）。因此**无法**靠「只在某些页面
           * import」来隔离 `style.css`——它必然出现在每个页面上。
           *
           * 所以「文档页回归原生」是靠**选择器作用域**实现的，而不是靠加载范围：
           * `src/css/scope-site-css.postcss.mjs` 在构建期给 `style.css` 的规则加一层
           * `html:not(.docs-wrapper)` 守卫，文档页（`<html class="docs-wrapper …">`）因此
           * 完全不受站点样式影响，拿到干净的 Infima。
           */
          customCss: ["./src/css/style.css", "./src/css/docusaurus-overrides.css"],
        },
        sitemap: { changefreq: "weekly", priority: 0.5 },
      },
    ],
  ],

  plugins: [
    ...LANGUAGES.map((lang) => docsPlugin(lang)),
    marketSourceDevPlugin,
    // 给 style.css 的规则加 `html:not(.docs-wrapper)` 作用域，让文档页保持纯 Infima。
    scopeSiteCssPlugin,
  ],

  themeConfig: {
    colorMode: {
      /**
       * 本分支交给**原生** ColorModeToggle：`disableSwitch: false` 让 Navbar 右侧出现
       * Docusaurus 原生的明暗切换按钮（此前站点用自己的 ThemeToggle 写 `data-theme`）。
       */
      disableSwitch: false,
      respectPrefersColorScheme: true,
      defaultMode: "light",
    },
    /**
     * 原生 Navbar / Footer 的链接来自 `themeConfig`，而它**在构建期就固定**，
     * 无法按 URL 变语言。本站是 `/zh-CN/…` 与 `/en-US/…` 双前缀，所以这里先按 zh-CN
     * 填写以获得原生观感；双语切换能力不在本分支的试验范围内（见分支说明）。
     */
    navbar: {
      title: "Flowy Agent Store",
      hideOnScroll: false,
      items: [
        { to: "/zh-CN/market", label: "市场", position: "left" },
        { to: "/zh-CN/docs", label: "文档", position: "left" },
        {
          href: "https://github.com/Michael-Lfx/allo",
          label: "GitHub",
          position: "right",
        },
        {
          href: "https://github.com/szStarWave/agent-store-site/releases",
          label: "下载",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "文档",
          items: [
            { label: "快速开始", to: "/zh-CN/docs/quick-start" },
            { label: "命令行用法", to: "/zh-CN/docs/cli" },
            { label: "配置文件", to: "/zh-CN/docs/configuration" },
            { label: "TypeScript SDK", to: "/zh-CN/docs/typescript-sdk" },
          ],
        },
        {
          title: "资源",
          items: [
            { label: "市场", to: "/zh-CN/market" },
            {
              label: "发布",
              href: "https://github.com/szStarWave/agent-store-site/releases",
            },
            { label: "GitHub", href: "https://github.com/Michael-Lfx/allo" },
          ],
        },
      ],
      copyright: "© Flowy Agent Store 贡献者。本站点与运行时以本地优先为原则。",
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      // 与旧站一致的围栏语言集合。**不含 `jsonc`**：Prism 没有 jsonc 语法包，
      // 写进来会让 prism-include-languages 的 require 失败并中断构建；
      // 它由 src/clientModules/prism-jsonc.ts 以 json 的别名补上。
      additionalLanguages: ["bash", "json", "toml"],
    },
  },

  /** `jsonc` 别名必须发生在主题装配 Prism 之后，因此走客户端模块注入。 */
  clientModules: ["./src/clientModules/prism-jsonc.ts"],

  /** 供测试与维护脚本读取的构建期数据。 */
  customFields: {
    docOrder: DOC_ORDER.map((entry) => entry.slug),
    languages: [...LANGUAGES],
  },
};

export default config;
