import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import { DOC_ORDER } from "./src/lib/docOrder";

/**
 * 文档侧边栏 —— 顺序**由 `src/lib/docOrder.ts` 生成**，不在这里手写第二份。
 *
 * ## 为什么需要这个文件
 *
 * 不写 `sidebarPath` 时，docs 插件用内置的 `DefaultSidebars`
 * （`[{ type: 'autogenerated', dirName: '.' }]`），而自动生成的顺序是
 * **按文件名（slug）字母序**。于是侧边栏成了
 * `architecture → changelog → cli → compatibility → configuration → examples-sdk → …`，
 * 与首页「快速开始」打头的引导顺序完全不符。
 *
 * 而 `src/lib/docOrder.ts` 里早就登记了预期顺序，页脚与文档索引页都在用它——
 * 只有侧边栏漏了。这里补上，让三者共用同一个真源：改顺序只改 `DOC_ORDER` 一处。
 *
 * ## 为什么标签不用 i18n 词条
 *
 * `{ type: 'doc', id }` 的显示名默认取自该文档的 h1（`快速开始` / `Quick start`）。
 * 本站是「单 locale + 两个 docs 插件实例」，中英文各读自己的目录，于是**标签天然是一对**，
 * 不需要（也无法）在构建期静态配置里写双语标签。
 *
 * ## 两个语言实例共用本文件
 *
 * 中英目录的文件名完全一致（`check:docs-sync` 的门禁保证了这点），doc id 因此相同，
 * 同一个 sidebars 文件对两个实例都成立。
 */
const sidebars: SidebarsConfig = {
  // 键名必须是 `defaultSidebar`：不指定 `sidebarPath` 时插件用的就是这个键
  // （见 `@docusaurus/plugin-content-docs` 的 `DefaultSidebars`）。
  defaultSidebar: DOC_ORDER.map(({ slug }) => ({ type: "doc", id: slug })),
};

export default sidebars;
