"""Cloud-vendor agent allowlist loader.

External-release editions of this skill ship with an empty allowlist so that no
specific cloud vendor's brand or product names are embedded in the source code.
Operators can populate ``config/cloud_vendor_processes.json`` (path relative to
the skill root) to suppress noise generated by their cloud platform's
host-based agents during log condensation.

The loader is **fail-soft**: if the file is missing, malformed, or any field
is absent, the affected category simply returns an empty collection and the
preanalyzers proceed as if no allowlist was configured.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# config/cloud_vendor_processes.json lives at <skill_root>/config/.
# This module sits at <skill_root>/scripts/analysis/_common/cloud_vendor.py,
# so the skill root is three parents up.
_SKILL_ROOT = Path(__file__).resolve().parents[3]
_CONFIG_PATH = _SKILL_ROOT / "config" / "cloud_vendor_processes.json"

_FIELDS = (
    "agent_processes",
    "agent_services",
    "iptables_chains",
    "initd_scripts",
    "file_path_noise",
)

_cache: dict[str, list[str]] | None = None


def _load() -> dict[str, list[str]]:
    """Load and cache the allowlist. Returns a dict with all known fields."""
    global _cache
    if _cache is not None:
        return _cache

    result: dict[str, list[str]] = {field: [] for field in _FIELDS}
    try:
        with _CONFIG_PATH.open("r", encoding="utf-8") as f:
            raw: Any = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        _cache = result
        return result

    if isinstance(raw, dict):
        for field in _FIELDS:
            value = raw.get(field)
            if isinstance(value, list):
                # Coerce to list[str] and drop non-string entries silently.
                result[field] = [str(item) for item in value if isinstance(item, str)]

    _cache = result
    return result


def agent_processes() -> set[str]:
    """Cloud agent process-name fragments (substring match)."""
    return set(_load()["agent_processes"])


def agent_services() -> tuple[str, ...]:
    """Cloud agent systemd service-name fragments (substring match)."""
    return tuple(_load()["agent_services"])


def iptables_chains() -> set[str]:
    """Cloud HIDS iptables chain names (exact match)."""
    return set(_load()["iptables_chains"])


def initd_scripts() -> set[str]:
    """Cloud agent init.d script-name fragments (substring match)."""
    return set(_load()["initd_scripts"])


def file_path_noise() -> tuple[str, ...]:
    """Cloud agent file-path fragments to ignore in mtime/ctime scans."""
    return tuple(_load()["file_path_noise"])


def reset_cache() -> None:
    """Clear the cache. Mainly useful for tests."""
    global _cache
    _cache = None
