#!/usr/bin/env node
"use strict";

/**
 * One-click installer for kwiki-cli (channel distribution).
 *
 * This script is auto-generated by scripts/pack-dist.js.
 * It downloads the platform-specific tgz from CDN and installs it globally via npm.
 *
 * Usage:
 *   node install.js
 */

const https = require("https");
const http = require("http");
const { join } = require("path");
const { existsSync, mkdirSync, createWriteStream, copyFileSync, readdirSync, unlinkSync, writeFileSync } = require("fs");
const { spawnSync } = require("child_process");
const { homedir, tmpdir } = require("os");

// ---- injected by pack-dist.js ----
const VERSION = "2.0.3";
const CDN_VERSION = "v2.0.3-20260803075737";
const SOURCE = "workbuddy";
const CDN_BASE = "https://personal.wpscdn.cn/app/kwiki-cli/beta";
const SKILL_DIR = "wps-knowledgebase";
// ---- end injected ----

const PLATFORM_MAP = { darwin: "darwin", linux: "linux", win32: "windows" };
const ARCH_MAP = { x64: "amd64", arm64: "arm64" };

function download(url, dest) {
  return new Promise((resolve, reject) => {
    const file = createWriteStream(dest);
    const get = url.startsWith("https") ? https.get : http.get;
    get(url, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        file.close();
        return download(res.headers.location, dest).then(resolve, reject);
      }
      if (res.statusCode !== 200) {
        file.close();
        return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
      }
      res.pipe(file);
      file.on("finish", () => file.close(resolve));
      file.on("error", reject);
    }).on("error", reject);
  });
}

function copyDirRecursive(src, dest) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src, { withFileTypes: true })) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      copyFileSync(srcPath, destPath);
    }
  }
}

function installSkillPackage(scriptDir, destSkillsBase) {
  const skillMd = join(scriptDir, "SKILL.md");
  const refsSrc = join(scriptDir, "references");
  const destSkill = join(destSkillsBase, SKILL_DIR);
  mkdirSync(destSkill, { recursive: true });

  if (!existsSync(skillMd)) return false;

  copyFileSync(skillMd, join(destSkill, "SKILL.md"));
  if (existsSync(refsSrc)) {
    copyDirRecursive(refsSrc, join(destSkill, "references"));
  }
  return true;
}

async function main() {
  console.log(`\nkwiki-cli installer (v${VERSION}${SOURCE ? ", source: " + SOURCE : ""})\n`);

  const platform = PLATFORM_MAP[process.platform];
  const arch = ARCH_MAP[process.arch];
  if (!platform || !arch) {
    console.error(`Unsupported platform: ${process.platform}/${process.arch}`);
    console.error("Supported: darwin/arm64, darwin/x64, linux/x64, linux/arm64, windows/x64, windows/arm64");
    process.exit(1);
  }

  const tgzName = `kwiki-cli-${platform}-${arch}-${VERSION}.tgz`;
  const tgzUrl = `${CDN_BASE}/${CDN_VERSION}/${tgzName}`;
  const tgzPath = join(tmpdir(), tgzName);

  console.log(`  Platform     ${platform}/${arch}`);
  console.log(`  Downloading  ${tgzUrl}`);

  try {
    await download(tgzUrl, tgzPath);
  } catch (err) {
    console.error(`\n  Failed to download: ${err.message}`);
    process.exit(1);
  }
  console.log(`  Saved to     ${tgzPath}`);

  console.log(`  Installing   npm install -g ${tgzPath}`);
  const r = spawnSync("npm", ["install", "-g", tgzPath], {
    stdio: "inherit",
    shell: true,
  });
  if (r.status !== 0) {
    console.error("\n  npm install -g failed (exit " + r.status + ")");
    process.exit(r.status || 1);
  }

  try { unlinkSync(tgzPath); } catch {}

  // Persist source in ~/.kwiki-cli/config.json (skip when no source)
  if (SOURCE) {
    const configDir = join(homedir(), ".kwiki-cli");
    try {
      mkdirSync(configDir, { recursive: true });
      const configPath = join(configDir, "config.json");
      let cfg = {};
      try { cfg = JSON.parse(require("fs").readFileSync(configPath, "utf8")); } catch {}
      cfg.source = SOURCE;
      writeFileSync(configPath, JSON.stringify(cfg, null, 2) + "\n");
      console.log(`  ✓ Config        ${configPath}`);
    } catch (e) {
      console.error(`  ⚠ Failed to write config.json: ${e.message}`);
    }
  }

  // Copy skill package (SKILL.md + references/) to agent directories
  const scriptDir = __dirname;
  const targets = [
    { name: "Cursor", dir: join(homedir(), ".cursor", "skills") },
    { name: "Claude Code", dir: join(homedir(), ".claude", "skills") },
    { name: "OpenClaw", dir: join(homedir(), ".openclaw", "skills") },
    { name: "Kimi", dir: process.env.KWIKI_KIMI_SKILLS_DIR || join(homedir(), ".kimi", "skills") },
  ];

  if (existsSync(join(scriptDir, "SKILL.md"))) {
    for (const target of targets) {
      try {
        if (installSkillPackage(scriptDir, target.dir)) {
          console.log(`  ✓ ${target.name} Skill (${SKILL_DIR}) → ${join(target.dir, SKILL_DIR)}`);
        }
      } catch {}
    }
  }

  console.log(`\n  ✔ kwiki-cli v${VERSION} installed successfully.`);
  if (SOURCE) {
    console.log(`    Channel source "${SOURCE}" persisted to ~/.kwiki-cli/config.json`);
  }
  console.log();
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
